// DOM-level fallback tests. These do not claim native Obsidian execution.
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {JSDOM} from 'jsdom';
import {markdownObsidianDouble} from './obsidian-markdown-double';
const bundled=await build({entryPoints:['src/main.ts'],bundle:true,write:false,format:'iife',globalName:'PluginUnderTest',platform:'browser',plugins:[{name:'obsidian-test-double',setup(b){b.onResolve({filter:/^obsidian$/},()=>({path:'obsidian',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:`${markdownObsidianDouble}
export class Modal { constructor(app){this.app=app;this.containerEl=document.createElement('div');this.modalEl=this.containerEl.createDiv();this.contentEl=this.modalEl.createDiv();}open(){document.body.append(this.containerEl);this.onOpen();}close(){this.onClose();this.containerEl.remove();}} export class ItemView{} export const getAllTags=()=>[]; export class PluginSettingTab {} export class Setting {} export class Plugin{} export class Notice{} export class TFile{} export class App{} export class Editor{} export class MarkdownView{}`,loader:'js'}));}}]});
const boot=()=>{
 const dom=new JSDOM('<body></body>',{runScripts:'outside-only'});const w=dom.window;(w as any).structuredClone=w.eval('(value)=>JSON.parse(JSON.stringify(value))');
 w.eval(`HTMLElement.prototype.empty=function(){this.replaceChildren()};HTMLElement.prototype.addClass=function(c){this.classList.add(c)};HTMLElement.prototype.createEl=function(tag,o={}){const e=document.createElement(tag);if(o.text!==undefined)e.textContent=o.text;if(o.cls)e.className=o.cls;for(const [k,v] of Object.entries(o.attr||{}))e.setAttribute(k,v);this.append(e);return e};HTMLElement.prototype.createDiv=function(o={}){return this.createEl('div',o)};`);
 w.eval(bundled.outputFiles[0].text+';window.PluginUnderTest=PluginUnderTest;');return {dom,w};
};
const flush=()=>new Promise(r=>setTimeout(r,0));
function setup(seed?:{front:string,back:string,sourcePath:string},persist?:(data:unknown)=>Promise<void>){const {w}=boot();Object.defineProperty(w.crypto,'randomUUID',{value:()=>`id-${Math.random()}`});let writes=0;const store=new(w as any).PluginUnderTest.CardStore(null,async(data:unknown)=>{writes++;if(persist)await persist(data);});const modal=new(w as any).PluginUnderTest.CardsModal({},store,()=>{},seed);modal.open();const button=(name:string)=>Array.from(w.document.querySelectorAll('button')).find(b=>b.textContent===name)!;return{w,store,modal,button,writes:()=>writes};}
test('seed editor cancel and close leave no card or write',()=>{const {store,button,writes}=setup({front:'问题',back:'答案',sourcePath:'a.md'});button('取消').click();assert.equal(store.cards.length,0);assert.equal(writes(),0);});
test('duplicate save clicks create one literal card and close',async()=>{let release!:()=>void;const {w,store,button,writes}=setup({front:'问题',back:'<img src=x onerror=alert(1)>答案👩🏽‍💻',sourcePath:'a.md'},()=>new Promise(r=>{release=r;}));const save=button('保存卡片');save.click();save.click();await flush();assert.equal(writes(),1);assert.equal(store.cards.length,0);release();await flush();assert.equal(store.cards.length,1);assert.equal(w.document.querySelectorAll('.pp-cards-modal').length,0);assert.equal(store.cards[0].back,'<img src=x onerror=alert(1)>答案👩🏽‍💻');});
test('reveal/rate/undo preserves hidden answers and repeated rating only saves once',async()=>{const {w,store,modal,button}=setup();await store.add('一个问题','秘密答案<img src=x>','x');modal.render();button('开始复习 1 张').click();assert.ok(!w.document.body.textContent!.includes('秘密答案'));assert.equal(w.document.querySelectorAll('.pp-flash-answer, img').length,0);button('揭晓答案').click();await flush();assert.ok(w.document.querySelector('.pp-flash-answer .pp-markdown-content')!.textContent!.includes('秘密答案'));assert.ok(w.document.querySelector('.pp-flash-answer .pp-markdown-content')!.textContent!.includes('图片未加载'));assert.equal(store.cards[0].back,'秘密答案<img src=x>');assert.equal(w.document.querySelectorAll('img').length,0);const rate=w.document.querySelector<HTMLButtonElement>('[aria-label="记住了 · 10 分钟后"]')!;rate.click();rate.click();await flush();assert.equal(store.cards[0].reviews,1);assert.match(w.document.body.textContent!,/这一轮，完成了/);button('撤销上次评分').click();await flush();assert.equal(store.cards[0].reviews,0);assert.ok(!w.document.body.textContent!.includes('秘密答案'));button('结束本轮').click();assert.equal(store.cards[0].reviews,0);});
test('failed save retains typed editor content and can retry',async()=>{let fail=true;const {w,store,button}=setup({front:'问题',back:'答案',sourcePath:''},async()=>{if(fail)throw new Error('磁盘写入失败');});button('保存卡片').click();await flush();assert.match(w.document.querySelector('[role="alert"]')!.textContent!,/保存失败/);assert.equal(w.document.querySelector<HTMLTextAreaElement>('[aria-label="背面 · 答案"]')!.value,'答案');assert.equal(store.cards.length,0);fail=false;button('保存卡片').click();await flush();assert.equal(store.cards.length,1);});
test('edit cancellation preserves progress and suspension can be reversed',async()=>{const {w,store,modal,button}=setup();await store.add('问题','答案','');modal.render();button('卡片库 · 1').click();button('暂停复习').click();await flush();assert.equal(store.cards[0].suspended,true);button('恢复复习').click();await flush();assert.equal(store.cards[0].suspended,false);button('编辑').click();const front=w.document.querySelector<HTMLTextAreaElement>('[aria-label="正面 · 问题"]')!;front.value='改掉的问题';front.dispatchEvent(new w.Event('input'));button('取消').click();assert.equal(store.cards[0].front,'问题');assert.equal(store.cards[0].reviews,0);});
test('closing during write waits for commit and then closes the seed editor',async()=>{let release!:()=>void;const {w,store,modal,button}=setup({front:'问题',back:'答案',sourcePath:''},()=>new Promise(r=>release=r));button('保存卡片').click();await flush();modal.close();assert.equal(w.document.querySelectorAll('.pp-cards-modal').length,1);release();await flush();assert.equal(store.cards.length,1);assert.equal(w.document.querySelectorAll('.pp-cards-modal').length,0);});
