// Isolated UI/state regression coverage; native Obsidian is verified separately.
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {JSDOM} from 'jsdom';
import {markdownObsidianDouble} from './obsidian-markdown-double';
import {parseNote} from '../src/study-source';
const bundle=await build({entryPoints:['src/main.ts'],bundle:true,write:false,format:'iife',globalName:'StructureTest',platform:'browser',plugins:[{name:'obsidian-structure-double',setup(b){
 b.onResolve({filter:/^obsidian$/},()=>({path:'obsidian',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:`${markdownObsidianDouble}
export class Modal {} export class Plugin {} export class Notice {} export class TFile {} export class App {} export class Editor {} export class MarkdownView {} export const getAllTags=()=>[];export class ItemView {constructor(leaf){this.app=leaf.app;this.containerEl=document.createElement('div');this.contentEl=this.containerEl.createDiv();this.containerEl.getBoundingClientRect=()=>({width:400,height:700});}addAction(){} async setState(){}}`,loader:'js'}));
}}]});
const flush=()=>new Promise<void>(resolve=>setTimeout(resolve,0));
function setup(text:string){
 const dom=new JSDOM('<body></body>',{runScripts:'outside-only'}),w=dom.window as any;
 w.eval(`HTMLElement.prototype.empty=function(){this.replaceChildren()};HTMLElement.prototype.addClass=function(c){this.classList.add(c)};HTMLElement.prototype.createEl=function(tag,o={}){const e=document.createElement(tag);if(o.text!==undefined)e.textContent=o.text;if(o.cls)e.className=o.cls;for(const[k,v]of Object.entries(o.attr||{}))e.setAttribute(k,v);this.append(e);return e};HTMLElement.prototype.createDiv=function(o={}){return this.createEl('div',o)};`);
 w.eval(bundle.outputFiles[0].text+';window.StructureTest=StructureTest;');
 let shield=false,writes=0;const source=text,note=parseNote(text,'学习/A.md');
 const app={vault:{getAllLoadedFiles:()=>[],getMarkdownFiles:()=>[],create:()=>{writes++;}},workspace:{rightSplit:{collapsed:false},requestSaveLayout(){}}};
 const host={app,currentPath:note.path,store:null,storageError:'',shield:(on:boolean)=>{shield=on;},activeEditor:()=>null};
 const view=new w.StructureTest.StudyView({app},host);view.notes=[note];view.refresh=async()=>{view.render();return true;};w.document.body.append(view.containerEl);
 const button=(label:string)=>[...w.document.querySelectorAll('button')].find((el:any)=>el.textContent===label)as HTMLButtonElement|undefined;
 const content=()=>w.document.body.textContent;const tab=(label:string)=>[...w.document.querySelectorAll('[role=tab]')].find((el:any)=>el.textContent.startsWith(label))as HTMLButtonElement;
 return{dom,w,view,note,button,content,tab,shield:()=>shield,writes:()=>writes,source,host};
}
import {CardStore} from '../src/card-store';
import {createCard} from '../src/cards';
test('review: card selections clear on filters, persist pages, and only selected cards suspend',async()=>{
 const s=setup('# Topic\ntext');try{const cards=Array.from({length:30},(_,i)=>createCard('Q'+i,'A','学习/A.md',1000,'id'+i));const store=new CardStore({version:2,cards},async()=>{});(s.host as any).store=store;s.view.studyScope={kind:'all',value:''};s.view.screen='library';s.view.render();s.button('全选本页')!.click();assert.equal(s.view.selectedCards.size,24);s.button('下一页')!.click();assert.equal(s.view.selectedCards.size,24);s.button('全选本页')!.click();assert.equal(s.view.selectedCards.size,30);
 const select=s.w.document.querySelector('[aria-label="卡片状态"]');select.value='due';select.dispatchEvent(new s.w.Event('change'));assert.equal(s.view.selectedCards.size,0);
 s.button('全选本页')!.click();s.button('批量暂停')!.click();s.button('确认暂停 24 张')!.click();await flush();assert.equal(store.cards.filter(c=>c.suspended).length,24);assert.equal(store.cards.filter(c=>!c.suspended).length,6);
 }finally{s.dom.window.close();}
});
test('review: final async card advance keeps recall focused',async()=>{const s=setup('# Topic\ntext');try{const cards=[createCard('Q','A','',1000,'id1')];(s.host as any).store=new CardStore({version:2,cards},async()=>{});await s.view.run(async()=>{},()=>s.view.startCards(cards));assert.equal(s.w.document.activeElement,s.w.document.querySelector('textarea'));}finally{s.dom.window.close();}});
test('review: failed bulk persistence and stale later item are atomic',async()=>{let fail=false,writes=0;const cards=[createCard('Q','A','',1000,'one'),createCard('Q2','A2','',1000,'two')];const store=new CardStore({version:2,cards},async()=>{writes++;if(fail)throw Error('disk');});const before=JSON.stringify(store.cards);fail=true;await assert.rejects(store.suspendMany(cards,true));assert.equal(JSON.stringify(store.cards),before);fail=false;await store.edit('two',0,'changed','A',2000);const current=JSON.stringify(store.cards),priorWrites=writes;await assert.rejects(store.suspendMany(cards,true));assert.equal(JSON.stringify(store.cards),current);assert.equal(writes,priorWrites);});
import {LocationStore,parseLocations} from '../src/practice-location';
test('review: location writes serialize, omit extra answers and survive failed write',async()=>{let disk:any,writes=0,fail=true;const store=new LocationStore({version:1},async d=>{writes++;if(fail)throw Error('disk');disk=structuredClone(d);});const p:any={mode:'passage',path:'A.md',line:1,identity:'hash',sourceFingerprint:'1234567890abcdef',scope:{kind:'all',value:''},currentPath:'A.md',excludedPaths:[],answer:'secret',recall:'secret'};await assert.rejects(store.save(p));assert.equal(store.get('passage'),undefined);fail=false;await Promise.all([store.save(p),store.save({...p,line:2})]);assert.equal(store.get('passage')!.line,2);assert.equal(disk.passage.answer,undefined);assert.equal(disk.passage.recall,undefined);assert.throws(()=>parseLocations({version:1,passage:{...p,line:-1}}));});
test('review: suspend and resume preserve scheduling, lapse and learning counts',async()=>{const card={...createCard('Q','A','A.md',1000,'id'),reviews:9,lapses:3,intervalDays:14,dueAt:200000,lastReviewedAt:500,revision:3};let disk:any;const store=new CardStore({version:2,cards:[card]},async d=>disk=structuredClone(d));await store.suspendMany([card],true,3000);await store.suspendMany(store.cards,false,4000);const final=store.get('id')!;for(const k of ['reviews','lapses','intervalDays','dueAt','lastReviewedAt','front','back','sourcePath']as const)assert.equal(final[k],card[k]);assert.deepEqual(new CardStore(disk,async()=>{}).cards,store.cards);});
test('review: saved section resumes hidden and changed source is rejected',async()=>{const s=setup('# Topic\nOriginal answer that must stay hidden.');try{(s.host as any).locations=new LocationStore({version:1},async()=>{});s.view.beginPassage(s.note.passages[0]);await flush();s.button('揭晓并对照')!.click();s.button('返回学习')!.click();s.button('继续上次小节')!.click();await flush();assert.equal(s.view.screen,'passage');assert.equal(s.view.session.stage,'recall');assert.ok(!s.content().includes('Original answer'));s.button('返回学习')!.click();s.view.notes=[parseNote('# Topic\nChanged answer.',s.note.path)];s.view.render();s.button('继续上次小节')!.click();await flush();assert.equal(s.view.screen,'home');assert.match(s.view.message,/来源已变化/);}finally{s.dom.window.close();}});
test('review: whole section edited answer cloze saves directly into hidden card practice',async()=>{const s=setup('# Topic\nA stack uses LIFO ordering.');try{const store=new CardStore(null,async()=>{});(s.host as any).store=store;s.view.beginPassage(s.note.passages[0]);s.button('揭晓并对照')!.click();s.button('把本节制成卡片')!.click();s.view.draft.back='Updated stack uses LIFO ordering.';s.view.clozeTerm='LIFO';s.button('生成挖空草稿')!.click();assert.match(s.view.draft.front,/Updated/);assert.ok(!s.view.draft.front.includes('LIFO'));s.button('保存卡片')!.click();await flush();assert.equal(store.cards.length,1);assert.equal(s.view.screen,'card');assert.equal(s.view.revealed,false);assert.equal(s.w.document.querySelector('.pp-flash-answer'),null);assert.equal(s.w.document.activeElement,s.w.document.querySelector('textarea'));}finally{s.dom.window.close();}});
