import {test} from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {highlightRenderedComparison} from '../src/rendered-diff';
import {mountComparison} from '../src/comparison';
function pair(a:string,b:string){const dom=new JSDOM('<main><div id="a"></div><div id="b"></div></main>'),doc=dom.window.document;const left=doc.getElementById('a')!,right=doc.getElementById('b')!;left.innerHTML=a;right.innerHTML=b;return{dom,left,right};}
test('native reading structures retain full content and mark only omitted or added text',()=>{
 const s=pair('<p>主动回忆是<strong>暂时</strong>不看资料。</p><ul><li>先回想</li><li>再对照</li></ul><table><tr><td>完整答案</td></tr></table>','<p>主动回忆是<strong>一直</strong>不看资料。</p>');const a=s.left.textContent,b=s.right.textContent;highlightRenderedComparison(s.left,s.right);assert.equal(s.left.textContent,a);assert.equal(s.right.textContent,b);assert.equal(s.left.querySelectorAll('ul li').length,2);assert.equal(s.left.querySelectorAll('table td').length,1);assert.ok(s.left.querySelectorAll('mark.pp-diff-original').length);assert.ok(s.right.querySelectorAll('mark.pp-diff-recall').length);assert.equal(s.left.querySelector('strong')!.textContent,'暂时');s.dom.window.close();
});
test('equivalent visible text ignores bold and paragraph Markdown source differences',()=>{const s=pair('<p><strong>同一个答案</strong></p>','<p>同一个答案</p>');highlightRenderedComparison(s.left,s.right);assert.equal(s.left.querySelectorAll('mark').length,0);assert.equal(s.right.querySelectorAll('mark').length,0);s.dom.window.close();});
test('hidden UI and SVG contents do not contribute or receive invalid marks',()=>{const s=pair('<p>可见</p><span hidden>秘密</span><span aria-hidden="true">副本</span><span style="display:none">不可见</span><svg><text>图中文字</text></svg><button>复制</button>','<p>可见</p>');highlightRenderedComparison(s.left,s.right);assert.equal(s.left.querySelectorAll('mark').length,0);s.dom.window.close();});
test('math atom uses annotation and retains its original subtree',()=>{const s=pair('<p>公式 <span class="math"><span aria-hidden="true">x²</span><math><annotation>x^2</annotation></math></span></p>','<p>公式 <span class="math"><span aria-hidden="true">x³</span><math><annotation>x^3</annotation></math></span></p>');const atom=s.left.querySelector('.math')!,before=atom.innerHTML;highlightRenderedComparison(s.left,s.right);assert.equal(atom.innerHTML,before);assert.ok(atom.classList.contains('pp-diff-original'));assert.equal(atom.querySelectorAll('mark').length,0);s.dom.window.close();});
test('asynchronous two-sided render highlights only current generation and once',()=>{const dom=new JSDOM('<main></main>'),root=dom.window.document.querySelector('main')!,pending:Array<()=>void>=[];mountComparison(root,'原文','回忆','答案',true,()=>{},(parent,text,ready)=>{const host=parent.ownerDocument.createElement('p');host.textContent=text;parent.append(host);pending.push(()=>ready?.(host));return()=>host.remove();});pending[0]();assert.equal(root.querySelectorAll('mark').length,0);pending[1]();assert.equal(root.querySelectorAll('mark').length,2);pending[1]();assert.equal(root.querySelectorAll('mark mark').length,0);root.querySelector<HTMLButtonElement>('.pp-compare-mode')!.click();pending.forEach(run=>run());assert.equal(root.querySelectorAll('.pp-rich-content').length,0);dom.window.close();});
test('reverse completion and empty recall never mark the placeholder',()=>{for(const empty of [true,false]){const dom=new JSDOM('<main></main>'),root=dom.window.document.querySelector('main')!,pending:Array<()=>void>=[];mountComparison(root,'原文',empty?'':'回忆','答案',true,()=>{},(parent,text,ready)=>{const host=parent.ownerDocument.createElement('p');host.textContent=text;parent.append(host);pending.push(()=>ready?.(host));return()=>host.remove();});pending.slice().reverse().forEach(run=>run());assert.ok(root.querySelector('mark.pp-diff-original'));if(empty){assert.equal(root.querySelector('.pp-empty-answer')!.textContent,'（本轮未填写）');assert.equal(root.querySelectorAll('mark.pp-diff-recall').length,0);}dom.window.close();}});
