// Isolated UI/state regression coverage; native Obsidian is verified separately.
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {JSDOM} from 'jsdom';
import {markdownObsidianDouble} from './obsidian-markdown-double';
import {parseNote} from '../src/study-source';
const bundle=await build({entryPoints:['src/main.ts'],bundle:true,write:false,format:'iife',globalName:'StructureTest',platform:'browser',plugins:[{name:'obsidian-structure-double',setup(b){
 b.onResolve({filter:/^obsidian$/},()=>({path:'obsidian',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:`${markdownObsidianDouble}
export class Modal {} export class PluginSettingTab {} export class Setting {} export class Plugin {} export class Notice {} export class TFile {} export class App {} export class Editor {} export class MarkdownView {} export const getAllTags=()=>[];export class ItemView {constructor(leaf){this.app=leaf.app;this.containerEl=document.createElement('div');this.contentEl=this.containerEl.createDiv();this.containerEl.getBoundingClientRect=()=>({width:400,height:700});}addAction(){} async setState(){}}`,loader:'js'}));
}}]});
const flush=()=>new Promise<void>(resolve=>setTimeout(resolve,0));
function setup(text:string){
 const dom=new JSDOM('<body></body>',{runScripts:'outside-only'}),w=dom.window as any;w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.structuredClone=w.eval('(value)=>JSON.parse(JSON.stringify(value))');
 w.eval(`HTMLElement.prototype.empty=function(){this.replaceChildren()};HTMLElement.prototype.addClass=function(c){this.classList.add(c)};HTMLElement.prototype.createEl=function(tag,o={}){const e=document.createElement(tag);if(o.text!==undefined)e.textContent=o.text;if(o.cls)e.className=o.cls;for(const[k,v]of Object.entries(o.attr||{}))e.setAttribute(k,v);this.append(e);return e};HTMLElement.prototype.createDiv=function(o={}){return this.createEl('div',o)};`);
 w.eval(bundle.outputFiles[0].text+';window.StructureTest=StructureTest;');
 let shield=false,writes=0;const source=text,note=parseNote(text,'学习/A.md');
 const app={vault:{getAllLoadedFiles:()=>[],getMarkdownFiles:()=>[],create:()=>{writes++;}},workspace:{rightSplit:{collapsed:false},requestSaveLayout(){}}};
 const host={app,currentPath:note.path,store:null,storageError:'',shield:(on:boolean)=>{shield=on;},activeEditor:()=>null};
 const view=new w.StructureTest.StudyView({app},host);view.notes=[note];view.refresh=async()=>{view.render();return true;};w.document.body.append(view.containerEl);
 const button=(label:string)=>[...w.document.querySelectorAll('button')].find((el:any)=>el.textContent===label)as HTMLButtonElement|undefined;
 const content=()=>w.document.body.textContent;const tab=(label:string)=>[...w.document.querySelectorAll('[role=tab]')].find((el:any)=>el.textContent.startsWith(label))as HTMLButtonElement;
 return{dom,w,view,note,button,content,tab,shield:()=>shield,writes:()=>writes,source,host};
}
import {CardStore} from '../src/card-store';
import {createCard} from '../src/cards';

test('independent: SM2 Again repeats at most once, undo restores queue boundary and no synthetic scores',async()=>{
 const s=setup('# Topic\ntext');try{const store=new CardStore(null,async()=>{});s.host.store=store;await store.setSchedulingAlgorithm('sm2-osr');const first=await store.add('Q1','A1','',1000),second=await store.add('Q2','A2','',1000);s.view.retryAgain=true;s.view.startCards([first,second]);
 await s.view.rate(s.view.current,'again');assert.equal(s.view.current.id,second.id);assert.equal(store.get(first.id)!.reviews,1);
 await s.view.rate(s.view.current,'good');assert.equal(s.view.current.id,first.id);assert.equal(s.view.sessionTotal,3);assert.equal(s.view.repeatPass,true);assert.equal(store.get(first.id)!.reviews,1);
 s.button('撤销上次评分')!.click();await flush();assert.equal(s.view.current.id,second.id);assert.equal(s.view.sessionTotal,2);assert.equal(s.view.repeatPass,false);assert.equal(store.get(second.id)!.reviews,0);
 await s.view.rate(s.view.current,'good');assert.equal(s.view.current.id,first.id);await s.view.rate(s.view.current,'again');assert.equal(s.view.current,undefined);assert.equal(s.view.reviewed,3);assert.equal(store.get(first.id)!.reviews,2);assert.equal(store.get(second.id)!.reviews,1);
 s.button('撤销上次评分')!.click();await flush();assert.equal(s.view.current.id,first.id);assert.equal(s.view.repeatPass,true);assert.equal(store.get(first.id)!.reviews,1);await s.view.rate(s.view.current,'again');assert.equal(s.view.current,undefined);assert.equal(store.get(first.id)!.reviews,2);
 }finally{s.dom.window.close();}
});
test('independent: FSRS future Again is not pulled early or synthetically rated',async()=>{const s=setup('# Topic\ntext');try{const store=new CardStore(null,async()=>{});s.host.store=store;const c=await store.add('Q','A','',1000);s.view.retryAgain=true;s.view.startCards([c]);await s.view.rate(s.view.current,'again');assert.equal(s.view.current,undefined);assert.equal(s.view.sessionTotal,1);assert.equal(store.get(c.id)!.reviews,1);assert.ok(store.get(c.id)!.dueAt>Date.now());assert.equal(store.get(c.id)!.fsrs!.logs.length,1);}finally{s.dom.window.close();}});
test('independent: failed rating leaves Again queue and undo state untouched; retry recovers',async()=>{const s=setup('# Topic\ntext');try{let fail=false;const store=new CardStore(null,async()=>{if(fail)throw Error('disk full')});s.host.store=store;await store.setSchedulingAlgorithm('sm2-osr');const c=await store.add('Q','A','',1000);s.view.retryAgain=true;s.view.startCards([c]);fail=true;await s.view.rate(s.view.current,'again');assert.equal(s.view.current.id,c.id);assert.equal(s.view.reviewed,0);assert.equal(s.view.againCandidates.size,0);assert.equal(s.view.undo,undefined);assert.equal(store.get(c.id)!.reviews,0);fail=false;await s.view.rate(s.view.current,'again');assert.equal(s.view.current.id,c.id);assert.equal(s.view.repeatPass,true);assert.equal(store.get(c.id)!.reviews,1);}finally{s.dom.window.close();}});
test('independent: passage navigation preserves unanswered draft and does not mount answer; restart clears it',async()=>{const s=setup('# One\nSecretOne\n\n# Two\nSecretTwo');try{const [one,two]=s.note.passages;s.view.passageQueue=[one,two];s.view.beginPassage(one);s.view.session.recall='My unsaved draft';s.view.beginPassage(two);assert.ok(!s.content().includes('SecretOne'));assert.ok(!s.content().includes('SecretTwo'));s.view.beginPassage(one);assert.equal(s.view.session.recall,'My unsaved draft');assert.equal(s.view.session.stage,'recall');assert.ok(!s.content().includes('SecretOne'));s.view.beginPassage(one,true);assert.equal(s.view.session.recall,'');s.view.session.recall='Erase on exit';s.view.home();await flush();s.view.beginPassage(one);assert.equal(s.view.session.recall,'');assert.equal(s.view.session.stage,'recall');assert.equal(s.writes(),0);}finally{s.dom.window.close();}});
test('independent: passage missed-point rounds survive navigation but hidden/close clears all draft sessions',async()=>{for(const stop of ['hide','close']){const s=setup('# One\nSecretOne\n\n# Two\nSecretTwo');try{const [one,two]=s.note.passages;s.view.beginPassage(one);s.view.session.recall='First attempt';s.view.session.reveal();s.view.session.missed='Missing one';s.view.session.retry();s.view.session.recall='Retry answer';s.view.passageSaved=true;s.view.beginPassage(two);s.view.beginPassage(one);assert.equal(s.view.session.recall,'Retry answer');assert.equal(s.view.session.target,'Missing one');assert.equal(s.view.session.rounds.length,1);assert.equal(s.view.passageSaved,true);assert.equal(s.view.session.stage,'recall');assert.ok(!s.content().includes('SecretOne'));if(stop==='hide'){s.view.containerEl.getBoundingClientRect=()=>({width:0,height:0});s.view.visibilityChanged();assert.equal(s.view.session,null);assert.equal(s.view.screen,'home');}else await s.view.onClose();assert.equal(s.view.passageDrafts.size,0);assert.equal(s.shield(),false);assert.equal(s.writes(),0);}finally{s.dom.window.close();}}});
test('independent: settings use CardStore source of truth, successful persist survives restart and failed persist rolls dropdown back',async()=>{
 const bundle=await build({entryPoints:['src/settings.ts'],bundle:true,write:false,format:'iife',globalName:'SettingsReview',platform:'browser',plugins:[{name:'settings-double',setup(b){b.onResolve({filter:/^obsidian$/},()=>({path:'obsidian',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:`export class App {} export class Notice {constructor(t){window.notice=t}} export class PluginSettingTab {constructor(app,plugin){this.containerEl=document.createElement('div')}} export class Setting {constructor(root){this.root=root}setName(){return this}setDesc(){return this}addDropdown(fn){const el=document.createElement('select');this.root.append(el);const d={addOption(v,t){const o=document.createElement('option');o.value=v;o.textContent=t;el.append(o);return this},setValue(v){el.value=v;return this},setDisabled(v){el.disabled=v;return this},onChange(fn){el.addEventListener('change',()=>{window.pending=fn(el.value)});return this}};fn(d);return this}}`,loader:'js'}));}}]});
 const s=setup('# Topic\ntext');try{let disk:any,fail=false,refreshes=0;const store=new CardStore(null,async d=>{if(fail)throw Error('disk full');disk=structuredClone(d)});const c=await store.add('Q','A','',1000);await store.rate(c.id,c.revision,'good',2000);const cards=store.cards;s.w.eval(bundle.outputFiles[0].text+';window.SettingsReview=SettingsReview;');const host={store,refreshStudyViews(){refreshes++}};const tab=new s.w.SettingsReview.PracticeSettingTab({},host);tab.display();const select=tab.containerEl.querySelector('select');assert.equal(select.value,'fsrs');select.value='sm2-osr';select.dispatchEvent(new s.w.Event('change'));assert.equal(select.disabled,true);await s.w.pending;assert.equal(select.disabled,false);assert.equal(store.schedulingAlgorithm,'sm2-osr');assert.equal(new CardStore(disk,async()=>{}).schedulingAlgorithm,'sm2-osr');assert.deepEqual(store.cards,cards);assert.equal(refreshes,1);
 fail=true;select.value='fsrs';select.dispatchEvent(new s.w.Event('change'));await s.w.pending;assert.equal(select.value,'sm2-osr');assert.equal(store.schedulingAlgorithm,'sm2-osr');assert.equal(refreshes,1);assert.match(s.w.notice,/disk full|算法保存失败/);assert.deepEqual(store.cards,cards);
 }finally{s.dom.window.close();}
});
import {exportBackup} from '../src/backup';
test('independent: restore UI requires algorithm choice, blocks stale controls and retries same failed plan without losing cards',async()=>{const s=setup('# Topic\ntext');try{let fail=false;const local=new CardStore(null,async()=>{if(fail)throw Error('disk full')});s.host.store=local;await local.setSchedulingAlgorithm('fsrs');const original=await local.add('Local','Original','',1000);const source=new CardStore(null,async()=>{});await source.setSchedulingAlgorithm('sm2-osr');await source.add('Incoming','Answer','',1000);s.view.screen='backup';s.view.backupText=exportBackup(source.data);s.view.render();s.button('预览合并结果')!.click();const prior=s.button('确认合并 1 张卡片')!;assert.equal(prior.disabled,true);const select=s.w.document.querySelector('[aria-label="恢复后的复习算法"]');assert.equal(select.value,'');select.value='use-backup';select.dispatchEvent(new s.w.Event('change'));const confirm=s.button('确认合并 1 张卡片')!;assert.equal(confirm.disabled,false);prior.click();await flush();assert.equal(local.cards.length,1);fail=true;confirm.click();await flush();assert.equal(local.cards.length,1);assert.equal(local.schedulingAlgorithm,'fsrs');assert.ok(s.view.importPlan);fail=false;s.button('确认合并 1 张卡片')!.click();await flush();assert.equal(local.cards.length,2);assert.equal(local.schedulingAlgorithm,'sm2-osr');assert.deepEqual(local.get(original.id),original);}finally{s.dom.window.close();}});
test('independent: interrupted multipart export reports incomplete backup without touching card state or Markdown',async()=>{const s=setup('# Topic\ntext');try{const cards=Array.from({length:220},(_,i)=>createCard('Large '+i,'x'.repeat(49000),'source.md',1000,'large'+i));const local=new CardStore({version:2,cards},async()=>{throw Error('unexpected state write')});s.host.store={get data(){return s.w.JSON.parse(JSON.stringify(local.data))}};Object.defineProperty(s.w.crypto,'randomUUID',{value:()=> 'multipart-test-id'});const files=new Map<string,string>();let writes=0;s.host.app.vault.getAbstractFileByPath=(p:string)=>files.has(p)?{}:null;s.host.app.vault.createFolder=async(p:string)=>{files.set(p,'folder')};s.host.app.vault.create=async(p:string,t:string)=>{assert.ok(p.startsWith('Passage Practice backups/')&&p.endsWith('.json'));if(++writes===2)throw Error('disk');files.set(p,t)};const before=local.data;s.view.screen='backup';s.view.render();s.button('导出 JSON 到本地知识库')!.click();await flush();await flush();assert.match(s.view.message,/已写 1 \/ 2 卷.*不是完整备份/);assert.deepEqual(local.data,before);assert.equal(writes,2);}finally{s.dom.window.close();}});
