import {SchedulingAlgorithm} from './spaced-repetition';
import {ReviewOrder,sessionOrder,sessionFrom} from './review-order';
import {resolvePassageSourceLine,resolveCardSourceLine} from './source-location';
import {intervalLabel} from './interval';
import {DEFAULT_DECK} from './decks';
import {filterCards,sameCard,CardStatus,NO_SOURCE} from './card-management';
import {LocationStore,PracticeLocation} from './practice-location';
import {MarkdownPreviewScope} from './markdown-preview';
import {studyStats,locateEvidence} from './study-health';
import {OutlineBranch} from './outline';
import {makeCloze,keywordSuggestions} from './cloze';
import {exportBackupParts,MAX_BACKUP_BYTES,ImportAlgorithmChoice,parseBackup,planImport,ImportPlan} from './backup';
import {excluded,parseExclusions,paginate,matchesQuery,noteTags} from './catalog';
import {KnowledgePoint,extractKnowledge,uniqueKnowledge,EXTRACTOR_VERSION,MAX_NOTE_BYTES,fingerprint} from './knowledge';
import {App,ItemView,MarkdownView,Notice,TFile,WorkspaceLeaf,getAllTags} from 'obsidian';
import {Card,Rating,applyRating,dueCards,srHistogram,activeAlgorithm} from './cards';
import {CardStore} from './card-store';
import {CardSeed} from './card-modal';
import {Session,createReview,reviewNote} from './core';
import {mountComparison} from './comparison';
import {Scope,NoteIndex,Passage,passageSourceRef,selectionSourceRef,cardMarkup,matchesScope,parseNote,studyCards} from './study-source';
export const STUDY_VIEW='passage-practice-study';
export interface StudyHost {locations?:LocationStore|null;locationError?:string;app:App;store:CardStore|null;storageError:string;currentPath:string;shield(on:boolean):void;insertCard(seed:CardSeed):Promise<void>;activeEditor():MarkdownView|null}
interface SourceValidation {point:KnowledgePoint;file:TFile;path:string;mtime:number;size:number}
const ratingLabels:Record<Rating,string>={again:'忘了',hard:'困难',good:'记住了',easy:'轻松'};
const date=(n:number)=>new Date(n).toLocaleString('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'});
export class StudyView extends ItemView {
 private previews=new MarkdownPreviewScope(this.app);
 private renderedScreen='';private clockTimer:number|undefined;private relearn=false;
 private visibilityObserver:MutationObserver|null=null;
 private selectedDeck='';private deckName='';
 private reviewOrder:ReviewOrder='sequential';
 private mode:'passage'|'outline'|'cards'|'knowledge'='passage';
 private screen:'home'|'passage'|'outline'|'card'|'edit'|'library'|'candidate'|'batch'|'backup'='home';
 private studyScope:Scope={kind:'current',value:''};
 private notes:NoteIndex[]=[];private scanWarnings:string[]=[];private loading=false;private scanId=0;private closed=false;private busy=false;private message='';
 private cache=new Map<string,{mtime:number;size:number;tags:string;version:number;note:NoteIndex}>();
 private indexedFiles:Array<{file:TFile;path:string;mtime:number;size:number}>=[];
 private scanProgress={done:0,total:0,reads:0,cached:0,milliseconds:0};
 private session:Session|null=null;private passage:Passage|null=null;private passageSaved=false;private compare=true;
 private passageQueue:Passage[]=[];private passagePosition=0;
 private passageDrafts=new Map<Passage,{session:Session;saved:boolean}>();
 private retryAgain=false;private againCandidates=new Set<string>();private repeatPass=false;
 private deckDeleteConfirm='';private configOpen=false;
 private outline:OutlineBranch|null=null;private outlineQueue:OutlineBranch[]=[];private outlinePosition=0;private outlineRevealed=0;private outlineRecall='';private outlineQuery='';private outlinePage=0;private outlineHistory:OutlineBranch[]=[];
 private queue:Card[]=[];private current:Card|undefined;private revealed=false;private recall='';private reviewed=0;private sessionTotal=0;
 private undo:{previous:Card;revision:number;queue:Card[];reviewed:number;total:number;again:string[];repeatPass:boolean}|undefined;
 private draft:CardSeed={front:'',back:'',sourcePath:''};private editCard:Card|undefined;private insert=false;private returnScreen:'home'|'library'|'card'|'passage'='home';private query='';
 private backupText='';private previewedBackupText='';private importPlan:ImportPlan|null=null;
 private cardStatus:CardStatus='all';private cardType:'all'|'snapshot'|'authored'='all';private cardSource='';private selectedCards=new Map<string,Card>();private bulkReview:{cards:Card[];suspended:boolean}|null=null;
 private selectedCandidates=new Map<string,KnowledgePoint>();private batch:KnowledgePoint[]=[];
 private candidateEditing=false;private clozeTerm='';private candidate:KnowledgePoint|null=null;private knowledgeQuery='';private knowledgePage=0;private knowledgeKind='structured';private hideSaved=true;private passageQuery='';private passagePage=0;private cardPage=0;private excludedPaths:string[]=[];
 constructor(leaf:WorkspaceLeaf,private host:StudyHost){super(leaf);}
 getViewType(){return STUDY_VIEW;}getDisplayText(){return '回想练习';}getIcon(){return 'book-open-check';}
 async onOpen(){this.contentEl.addClass('pp-study');this.visibilityObserver=new MutationObserver(()=>this.visibilityChanged());this.visibilityObserver.observe(this.app.workspace.containerEl,{attributes:true,subtree:true,attributeFilter:['class','style']});this.addAction('refresh-cw','刷新学习内容',()=>{if(!this.busy)void this.refresh(true);});await this.refresh();this.clockTimer=window.setInterval(()=>{if(this.screen==='home'&&this.mode==='cards'&&!this.configOpen&&!this.busy&&!this.loading&&!(this.contentEl.contains(document.activeElement)&&document.activeElement?.matches('input,textarea,select,[contenteditable=true]')))this.render();},30000);}
 async onClose(){window.clearInterval(this.clockTimer);this.visibilityObserver?.disconnect();this.visibilityObserver=null;this.closed=true;this.passageDrafts.clear();this.previews.reset();this.scanId++;this.host.shield(false);this.contentEl.empty();}
 getState(){return{reviewOrder:this.reviewOrder,mode:this.mode,selectedDeck:this.selectedDeck,scope:this.studyScope,excludedPaths:this.excludedPaths,knowledgeKind:this.knowledgeKind,hideSaved:this.hideSaved};}
 async setState(state:any,result:any){if(state?.reviewOrder==='random'||state?.reviewOrder==='sequential')this.reviewOrder=state.reviewOrder;if(typeof state?.selectedDeck==='string')this.selectedDeck=state.selectedDeck;if(state?.mode==='cards'||state?.mode==='passage'||state?.mode==='outline'||state?.mode==='knowledge')this.mode=state.mode;if(state?.scope&&['all','current','folder','tag'].includes(state.scope.kind)&&typeof state.scope.value==='string')this.studyScope=state.scope;if(Array.isArray(state?.excludedPaths))this.excludedPaths=parseExclusions(state.excludedPaths.filter((x:unknown)=>typeof x==='string').join('\n'));if(['all','structured','definition','list','explanation'].includes(state?.knowledgeKind))this.knowledgeKind=state.knowledgeKind;if(typeof state?.hideSaved==='boolean')this.hideSaved=state.hideSaved;await super.setState(state,result);if(!this.closed)void this.refresh();}
 private remember(){this.app.workspace.requestSaveLayout();}
 private visible(){const parents=new Set<unknown>();let parent=this.leaf?.parent;while(parent&&!parents.has(parent)){parents.add(parent);if((parent===this.app.workspace.rightSplit&&this.app.workspace.rightSplit.collapsed)||(parent===this.app.workspace.leftSplit&&this.app.workspace.leftSplit.collapsed))return false;parent=parent.parent;}const rect=this.containerEl.getBoundingClientRect();return rect.width>0&&rect.height>0;}
 visibilityChanged(){if(this.closed||this.visible())return;this.host.shield(false);if(this.busy||!['passage','outline','card'].includes(this.screen))return;this.screen='home';this.current=undefined;this.session=null;this.passageDrafts.clear();this.message='离开学习侧栏，未评分的练习与临时草稿已结束';this.render();}
 notifyChanged(){if(this.screen==='home'||this.screen==='library')void this.refresh();}
 async refresh(force=false,retry=0):Promise<boolean>{
  const token=++this.scanId,started=performance.now();this.loading=true;this.scanProgress={done:0,total:0,reads:0,cached:0,milliseconds:0};
  const notes:NoteIndex[]=[],warnings:string[]=[],files=this.app.vault.getMarkdownFiles().filter(file=>!excluded(file.path,['Passage Practice','Passage Practice backups',...this.excludedPaths]));this.scanProgress.total=files.length;
  const initialFiles=files.map(file=>({file,path:file.path,mtime:file.stat.mtime,size:file.stat.size}));if(this.screen==='home')this.render();
  let changedDuringRead=false,lastPaint=started;
  for(let i=0;i<files.length;i+=12){await Promise.all(files.slice(i,i+12).map(async file=>{const path=file.path,mtime=file.stat.mtime,size=file.stat.size;
   try{if(size>MAX_NOTE_BYTES){warnings.push(`超过 2 MiB，已跳过：${path}`);return;}
    const metadata=this.app.metadataCache.getFileCache(file)||{},tags=noteTags(getAllTags(metadata)||[],metadata.frontmatter),key=JSON.stringify(tags),cached=this.cache.get(path);let note:NoteIndex;
    if(!force&&cached&&cached.mtime===mtime&&cached.size===size&&cached.tags===key&&cached.version===EXTRACTOR_VERSION){note=cached.note;this.scanProgress.cached++;}
    else{const text=await(force?this.app.vault.read(file):this.app.vault.cachedRead(file));if(token!==this.scanId||this.closed)return;
     if(file.path!==path||file.stat.mtime!==mtime||file.stat.size!==size){changedDuringRead=true;return;}
     note=parseNote(text,path,tags);this.cache.set(path,{mtime,size,tags:key,version:EXTRACTOR_VERSION,note});this.scanProgress.reads++;
    }notes.push(note);
   }catch{if(token===this.scanId)warnings.push(`无法读取：${path}`);}
  }));if(token!==this.scanId||this.closed)return false;
   this.scanProgress.done=Math.min(i+12,files.length);if(performance.now()-lastPaint>80&&this.screen==='home'){this.render();lastPaint=performance.now();}
   // Yield to Obsidian between batches, including all-cache scans. Cancel stays clickable.
   if(i+12<files.length)await new Promise<void>(resolve=>window.setTimeout(resolve,0));
   if(token!==this.scanId||this.closed)return false;
  }
  const latest=this.app.vault.getMarkdownFiles().filter(file=>!excluded(file.path,['Passage Practice','Passage Practice backups',...this.excludedPaths])),latestSet=new Set(latest);if(latest.length!==initialFiles.length||initialFiles.some(item=>!latestSet.has(item.file)||item.file.path!==item.path||item.file.stat.mtime!==item.mtime||item.file.stat.size!==item.size))changedDuringRead=true;
  if(changedDuringRead){if(retry<2)return this.refresh(false,retry+1);this.loading=false;this.message='笔记仍在连续变化，已暂停扫描。请稍后刷新；本次结果未替换上次完整索引。';if(this.screen==='home')this.render();return false;}
  const existing=new Set(files.map(f=>f.path));for(const path of this.cache.keys())if(!existing.has(path))this.cache.delete(path);
  this.indexedFiles=initialFiles;this.notes=notes.sort((a,b)=>a.path.localeCompare(b.path,'zh-CN',{numeric:true})||(a.path<b.path?-1:a.path>b.path?1:0));this.scanWarnings=warnings;this.loading=false;this.scanProgress.milliseconds=Math.round(performance.now()-started);
  const valid=new Set(this.notes.flatMap(n=>n.knowledge||[]).map(p=>p.id));for(const id of this.selectedCandidates.keys())if(!valid.has(id))this.selectedCandidates.delete(id);
  if(this.screen==='home'||this.screen==='library')this.render();return true;
 }
 private cancelScan(){this.scanId++;this.loading=false;this.message='扫描已取消，保留上次完整结果；点击刷新可继续';this.render();}

 private cards(){const result=studyCards(this.notes,(this.host.store?.cards||[]).filter(c=>!excluded(c.sourcePath,this.excludedPaths)),this.studyScope,this.host.currentPath,Date.now());const deck=this.host.store?.decks?.find(d=>d.id===this.selectedDeck);if(this.selectedDeck&&!deck)this.selectedDeck='';if(deck){const members=new Set(deck.cardIds);result.cards=result.cards.filter(c=>members.has(c.id));}return result;}
 private selectedNotes(){return this.notes.filter(n=>matchesScope(n.path,n.tags,this.studyScope,this.host.currentPath));}
 private button(el:HTMLElement,text:string,action:()=>void,primary=false){const b=el.createEl('button',{text,cls:primary?'pp-primary':'pp-secondary'});b.type='button';b.disabled=this.busy;b.addEventListener('click',()=>{if(!this.busy&&!this.closed)action();});return b;}
 private field(el:HTMLElement,label:string,value:string,set:(value:string)=>void,placeholder='',max=50000){const w=el.createEl('label',{cls:'pp-field'});w.createEl('span',{text:label});const input=w.createEl('textarea',{attr:{'aria-label':label,placeholder,maxlength:String(max)}});input.value=value;input.disabled=this.busy;input.addEventListener('input',()=>set(input.value));return input;}
 private async run(action:()=>Promise<unknown>,success:()=>void){if(this.busy||this.closed)return;this.busy=true;this.message='';this.contentEl.setAttribute('aria-busy','true');this.contentEl.querySelectorAll<HTMLButtonElement|HTMLTextAreaElement|HTMLSelectElement>('button,textarea,select,input').forEach(e=>e.disabled=true);try{await action();if(!this.closed){this.busy=false;success();}}catch(e){this.message=e instanceof Error?e.message:'保存失败，请重试';if(this.closed)new Notice('保存未完成，请重新打开回想练习检查。');}finally{this.busy=false;if(!this.closed){this.visibilityChanged();this.render();if(this.screen==='card'&&!this.revealed||this.screen==='passage'&&this.session?.stage==='recall'||this.screen==='outline')this.focusRecall();}}}
 private home(){this.passageDrafts.clear();this.passageQueue=[];this.againCandidates.clear();this.selectedCards.clear();this.bulkReview=null;this.screen='home';this.current=undefined;this.session=null;this.host.shield(false);this.message='';void this.refresh();}
 private render(){if(this.closed)return;this.previews.reset();const root=this.contentEl;if(this.renderedScreen!==this.screen){root.scrollTop=0;this.renderedScreen=this.screen;}root.empty();root.setAttribute('aria-busy',String(this.busy));
  const top=root.createDiv({cls:'pp-study-heading'});const title=top.createDiv();title.createEl('span',{text:'回想练习',cls:'pp-study-title'});title.createEl('span',{text:'留一点时间，给记忆',cls:'pp-study-subtitle'});
  if(this.screen==='home'){const mode=root.createDiv({cls:'pp-mode-tabs',attr:{role:'tablist','aria-label':'学习模式'}});
  for(const [key,name,description]of [['passage','段落复习','按标题回忆整节'],['outline','大纲回忆','父节点 → 子分支'],['cards','问答卡片','问题与答案'],['knowledge','知识提炼','预览再制卡']]as const){const b=this.button(mode,'',()=>{if(this.screen!=='home')return;this.mode=key;this.selectedCandidates.clear();this.remember();this.render();});b.setAttribute('role','tab');b.setAttribute('aria-selected',String(this.mode===key));b.tabIndex=this.mode===key?0:-1;b.addEventListener('keydown',event=>{if(this.screen!=='home'||this.busy||!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const keys=['passage','outline','cards','knowledge']as const,index=keys.indexOf(this.mode);this.mode=event.key==='Home'?'passage':event.key==='End'?'knowledge':keys[(index+(event.key==='ArrowRight'?1:3))%4];this.selectedCandidates.clear();this.remember();this.render();this.contentEl.querySelector<HTMLElement>('[role=tab][aria-selected=true]')?.focus();});b.createEl('strong',{text:name});b.createEl('span',{text:description});if(this.mode===key)b.addClass('is-active');b.disabled=this.busy||this.screen!=='home';}}
  if(this.message){const positive=/^(?:已|卡片已|离开)/.test(this.message);root.createEl('p',{text:this.message,cls:positive?'pp-notice':'pp-error',attr:{role:positive?'status':'alert'}});}
  if(this.screen==='home'){if(this.mode==='cards'&&!this.loading)this.renderCardPrimary(root);const config=root.createEl('details',{cls:'pp-home-config'});config.open=this.configOpen;config.addEventListener('toggle',()=>{if(config.isConnected)this.configOpen=config.open;});config.createEl('summary',{text:'学习范围、卡组与顺序 · '+(this.studyScope.kind==='current'?'当前笔记':this.studyScope.kind==='all'?'整个知识库':this.studyScope.value)});this.renderScope(config);if(this.mode==='cards'||this.mode==='knowledge')this.renderDecks(config);if(['passage','outline','cards'].includes(this.mode))this.renderReviewOptions(config);this.renderHome(root);}else{const bar=root.createDiv({cls:'pp-session-bar'});bar.createEl('span',{text:this.screen==='passage'?'段落复习':this.screen==='outline'?'大纲回忆':this.screen==='card'?'问答卡片':this.screen==='library'?'卡片管理':'明确问题与答案'});this.button(bar,this.screen==='edit'?'取消编辑':'返回学习',()=>{if(this.screen==='edit')this.cancelEdit();else this.home();});if(this.screen==='passage')this.renderPassage(root);else if(this.screen==='outline')this.renderOutline(root);else if(this.screen==='card')this.renderCard(root);else if(this.screen==='edit')this.renderEditor(root);else if(this.screen==='candidate')this.renderCandidate(root);else if(this.screen==='batch')this.renderBatch(root);else if(this.screen==='backup')this.renderBackup(root);else this.renderLibrary(root);}
 }
 private renderReviewOptions(root:HTMLElement){
  const box=root.createDiv({cls:'pp-scope pp-review-options'});box.createEl('label',{text:'复习顺序'});const order=box.createEl('select',{attr:{'aria-label':'复习顺序'}});order.createEl('option',{text:'顺序复习',attr:{value:'sequential'}});order.createEl('option',{text:'乱序复习',attr:{value:'random'}});order.value=this.reviewOrder;order.addEventListener('change',()=>{this.reviewOrder=order.value as ReviewOrder;this.remember();this.render();});
  if(this.mode==='cards'){const row=box.createEl('label',{cls:'pp-relearn'}),check=row.createEl('input',{attr:{type:'checkbox','aria-label':'本轮再练忘了的卡片'}});check.checked=this.retryAgain;check.addEventListener('change',()=>this.retryAgain=check.checked);row.createEl('span',{text:'本轮结束后，再练一次「忘了」且已到期的卡片'});box.createEl('p',{text:'每张最多追加一次，不提前练未到期卡片；算法在 Obsidian 设置 → Passage Practice（回想练习）中选择。',cls:'pp-footnote'});}
  box.createEl('p',{text:this.mode==='cards'?'只复习已到期卡片；乱序会打乱本轮顺序。':this.reviewOrder==='random'?'本轮随机排列，上一节与下一节保持同一顺序。':'按笔记、小节的原有顺序复习。',cls:'pp-footnote'});
 }
 private renderDecks(root:HTMLElement){const store=this.host.store;if(!store)return;const box=root.createDiv({cls:'pp-scope'});box.createEl('label',{text:'卡组',attr:{for:'pp-deck'}});const select=box.createEl('select',{attr:{id:'pp-deck','aria-label':'选择卡组'}});select.createEl('option',{text:'全部卡组',attr:{value:''}});for(const deck of store.decks||[])select.createEl('option',{text:`${deck.name} · ${deck.cardIds.length} 张`,attr:{value:deck.id}});select.value=this.selectedDeck;select.addEventListener('change',()=>{this.selectedDeck=select.value;this.selectedCards.clear();this.remember();this.render();});
 const controls=box.createEl('details');controls.createEl('summary',{text:'新建卡组'});const name=controls.createEl('input',{attr:{'aria-label':'新卡组名称',maxlength:'100',placeholder:'例如：数据结构'}});name.value=this.deckName;name.addEventListener('input',()=>this.deckName=name.value);this.button(controls,'创建空卡组',()=>void this.run(async()=>{const deck=await store.createDeck(this.deckName);this.selectedDeck=deck.id;this.deckName='';},()=>{this.remember();this.message='已创建卡组';}));box.createEl('p',{text:'新卡片保存到所选卡组；选「全部卡组」时保存到默认卡组。',cls:'pp-footnote'});
 const deck=store.decks.find(d=>d.id===this.selectedDeck);if(deck){const manage=box.createEl('details');manage.createEl('summary',{text:'管理当前卡组'});const rename=manage.createEl('input',{attr:{'aria-label':'卡组新名称',maxlength:'100'}});rename.value=deck.name;this.button(manage,'保存卡组名称',()=>void this.run(()=>store.renameDeck(deck.id,deck.revision,rename.value),()=>{this.message='已重命名卡组';}));
 if(deck.id!==DEFAULT_DECK){const del=this.button(manage,'删除空卡组',()=>{this.deckDeleteConfirm=deck.id;this.render();});del.disabled=!!deck.cardIds.length||this.busy;if(deck.cardIds.length)manage.createEl('p',{text:'只能删除空卡组，可在管理卡片中移出成员；卡片和评分不会删除。',cls:'pp-footnote'});}
 if(this.deckDeleteConfirm===deck.id){manage.open=true;const confirm=manage.createDiv({cls:'pp-bulk-confirm'});confirm.createEl('p',{text:`确认删除空卡组「${deck.name}」？只删除卡组定义，卡片和评分保留。`});this.button(confirm,'取消删除卡组',()=>{this.deckDeleteConfirm='';this.render();});this.button(confirm,'确认删除空卡组',()=>void this.run(()=>store.deleteEmptyDeck(deck.id,deck.revision),()=>{this.selectedDeck='';this.deckDeleteConfirm='';this.remember();this.message='已删除空卡组，卡片与评分保留';}));}}
 }
 private renderScope(root:HTMLElement){const box=root.createDiv({cls:'pp-scope'});box.createEl('label',{text:'学习范围',attr:{for:'pp-scope-kind'}});const select=box.createEl('select',{attr:{id:'pp-scope-kind','aria-label':'学习范围'}});for(const[k,v]of [['current','当前笔记'],['folder','按文件夹'],['tag','按标签'],['all','整个知识库']])select.createEl('option',{text:v,attr:{value:k}});select.value=this.studyScope.kind;select.addEventListener('change',()=>{this.selectedCandidates.clear();this.knowledgePage=0;this.passagePage=0;this.studyScope={kind:select.value as Scope['kind'],value:''};if(this.studyScope.kind==='folder')this.studyScope.value='/';if(this.studyScope.kind==='tag')this.studyScope.value=this.tags()[0]||'';this.remember();this.render();});
  if(this.studyScope.kind==='folder'||this.studyScope.kind==='tag'){const sub=box.createEl('select',{attr:{'aria-label':this.studyScope.kind==='folder'?'选择文件夹':'选择标签'}});const values=this.studyScope.kind==='folder'?this.folders():this.tags();if(!values.includes(this.studyScope.value))values.unshift(this.studyScope.value);for(const value of values)sub.createEl('option',{text:value?(value==='/'?'根目录（包含全部子文件夹）':(this.studyScope.kind==='tag'?'#':'')+value):'暂无标签',attr:{value}});sub.value=this.studyScope.value;sub.addEventListener('change',()=>{this.selectedCandidates.clear();this.knowledgePage=0;this.passagePage=0;this.studyScope.value=sub.value;this.remember();this.render();});box.createEl('p',{text:this.studyScope.kind==='folder'?'包含选中文件夹下的所有子文件夹':'同时包含子标签，例如 #学习 也包含 #学习/算法',cls:'pp-footnote'});}
  else box.createEl('p',{text:this.studyScope.kind==='current'?(this.host.currentPath||'先打开一篇笔记，或选择其他范围'):'包含所有 Markdown 笔记和本地快照卡片',cls:'pp-source-path'});
  const options=root.createEl('details',{cls:'pp-options'});options.createEl('summary',{text:this.excludedPaths.length?`索引选项 · 已排除 ${this.excludedPaths.length} 处`:'索引选项'});const input=this.field(options,'不参与学习的文件夹或文件（每行一个）',this.excludedPaths.join('\n'),()=>{},'例如：模板\n归档\n某篇笔记.md',4000);this.button(options,'应用排除范围',()=>{this.excludedPaths=parseExclusions(input.value);this.selectedCandidates.clear();this.remember();void this.refresh();});options.createEl('p',{text:'按完整路径边界排除，包含子文件夹；排除内容不会读取或进入提炼，不删除任何文件。',cls:'pp-footnote'});
 }
 private folders(){const set=new Set<string>(['/']);for(const item of this.app.vault.getAllLoadedFiles?.()||[])if('children' in item&&item.path!=='/')set.add(item.path);for(const n of this.notes){const parts=n.path.split('/');parts.pop();while(parts.length){set.add(parts.join('/'));parts.pop();}}return [...set].sort((a,b)=>a.localeCompare(b,'zh-CN'));}
 private tags(){const set=new Set<string>();for(const n of this.notes)for(const t of n.tags){const parts=t.replace(/^#/,'').split('/');while(parts.length){set.add(parts.join('/'));parts.pop();}}return [...set].sort((a,b)=>a.localeCompare(b,'zh-CN'));}
 private renderCardPrimary(root:HTMLElement){
  if(!this.host.store)return;const cards=this.cards().cards,due=dueCards(cards,Date.now()),row=root.createDiv({cls:'pp-primary-actions'});
  const start=this.button(row,due.length?`开始复习 ${due.length} 张`:'暂无到期卡片',()=>this.startCards(due),true);start.disabled=!due.length||this.busy;this.button(row,'新建卡片',()=>this.openEditor(),true);
  this.renderScopeCount(root,cards.length);
 }
 private renderScopeCount(root:HTMLElement,count:number){const deck=this.host.store?.decks.find(d=>d.id===this.selectedDeck);if(!deck){root.createEl('p',{text:`本范围 ${count} 张 · 全部卡组`,cls:'pp-footnote'});return;}
  root.createEl('p',{text:`${deck.name}：本范围 ${count} 张 / 全组 ${deck.cardIds.length} 张 · 同时应用学习范围与卡组`,cls:'pp-footnote'});
  if(this.studyScope.kind!=='all')this.button(root,'查看全组（切到整个知识库）',()=>{this.studyScope={kind:'all',value:''};this.selectedCards.clear();this.remember();this.render();});
 }
 private renderHome(root:HTMLElement){if(this.loading){root.createEl('p',{text:`正在读取 ${this.scanProgress.done} / ${this.scanProgress.total} 篇笔记…`,cls:'pp-muted',attr:{role:'status'}});const progress=root.createEl('progress',{attr:{max:String(this.scanProgress.total||1),value:String(this.scanProgress.done),'aria-label':'笔记扫描进度'}});progress.addClass('pp-scan-progress');this.button(root,'取消扫描',()=>this.cancelScan());return;}if(this.host.locationError)root.createEl('p',{text:this.host.locationError,cls:'pp-footnote'});if(this.mode==='passage'||this.mode==='outline')this.renderResume(root,this.mode);if(this.mode==='knowledge'){this.renderKnowledge(root);return;}if(this.mode==='outline'){this.renderOutlineHome(root);return;}const notes=this.selectedNotes(),passages=notes.flatMap(n=>n.passages),deck=this.cards(),due=dueCards(deck.cards,Date.now());
  const counts=root.createDiv({cls:'pp-study-stats'});for(const[count,label]of(this.mode==='passage'?[[notes.length,'篇笔记'],[passages.length,'个小节']]:[[deck.cards.length,'张卡片'],[due.length,'张到期']])as[number,string][]){const tile=counts.createDiv();tile.createEl('strong',{text:String(count)});tile.createEl('span',{text:label});}
  const intro=root.createDiv({cls:'pp-mode-intro'});intro.createEl('h2',{text:this.mode==='passage'?'一个标题，回忆完整一节':'一个问题，一张卡片'});intro.createEl('p',{text:this.mode==='passage'?(this.reviewOrder==='random'?'打乱熟悉的顺序，逐节回忆并核对。':'按笔记顺序逐节回忆，再揭晓原文核对。'):'先回忆，再揭晓答案，选择下次复习时间。'});
  if(this.mode==='passage'){
   const row=root.createDiv({cls:'pp-actions'});const pool=passages.filter(p=>matchesQuery([p.question,p.text,p.path],this.passageQuery));if(pool.length)this.button(row,this.reviewOrder==='random'?'开始乱序复习':'开始顺序复习',()=>{const pool=passages.filter(p=>matchesQuery([p.question,p.text,p.path],this.passageQuery));if(!pool.length){this.message='没有匹配的小节，请调整搜索';this.render();return;}this.passageQueue=sessionOrder(pool,this.reviewOrder);this.passagePosition=0;this.beginPassage(this.passageQueue[0]);},true);const selected=this.button(row,'练习编辑器选段',()=>this.selection(),true);selected.disabled=!this.currentEditor()||this.busy;
   this.button(row,'刷新内容',()=>void this.refresh(true));
   if(!passages.length)root.createEl('p',{text:'这个范围还没有可练习的小节。可切换范围，或打开笔记选择文字。属性和独立卡片标记不作为小节答案。',cls:'pp-empty'});
   else{root.createEl('h3',{text:'选择一个标题开始',cls:'pp-list-heading'});const search=root.createEl('input',{cls:'pp-search',attr:{type:'search','aria-label':'搜索小节',placeholder:'搜索正文、标题或路径'}});search.value=this.passageQuery;const list=root.createDiv({cls:'pp-passage-list'});const draw=()=>{list.empty();const filtered=passages.filter(p=>matchesQuery([p.question,p.text,p.path],this.passageQuery)),page=paginate(filtered,this.passagePage);this.passagePage=page.page;for(const p of page.items){const b=this.button(list,'',()=>{const session=sessionFrom(filtered,p,this.reviewOrder);this.passageQueue=session.queue;this.passagePosition=session.position;this.beginPassage(p);});b.addClass('pp-passage-choice');b.createEl('span',{text:p.question,cls:'pp-item-title'});b.createEl('span',{text:p.headingPath?.join(' › ')||'无标题 · 全文复习',cls:'pp-item-preview'});b.createEl('span',{text:`${p.text.length.toLocaleString()} 字符`,cls:'pp-footnote'});b.createEl('span',{text:p.path,cls:'pp-source-path'});}this.pager(list,page,change=>{this.passagePage=change;draw();});};search.addEventListener('input',()=>{this.passageQuery=search.value;this.passagePage=0;draw();});draw();}
  }else{
   if(!this.host.store){root.createEl('p',{text:this.host.storageError,cls:'pp-error'});return;}
   const statistics=studyStats(deck.cards,Date.now()),detail=root.createEl('details',{cls:'pp-study-overview'});detail.createEl('summary',{text:`今天复习过 ${statistics.today} 张 · 暂停 ${statistics.paused} 张`});detail.createEl('p',{text:`尚未复习 ${statistics.new} 张 · 有过复习 ${statistics.reviewed} 张 · 未来 7 天到期 ${statistics.nextWeek} 张`});detail.createEl('p',{text:'根据你的评分安排下次复习。今天的数量按最近一次评分统计。'});
   const row=root.createDiv({cls:'pp-actions'});
   this.button(row,`管理卡片 · ${deck.cards.length}`,()=>{this.screen='library';this.render();});this.button(row,'备份与恢复',()=>{this.screen='backup';this.importPlan=null;this.backupText='';this.render();});
   const next=deck.cards.filter(c=>!c.suspended&&c.dueAt>Date.now()).sort((a,b)=>a.dueAt-b.dueAt)[0];if(next)root.createEl('p',{text:`下次到期 ${date(next.dueAt)} · 自动更新到期数量`,cls:'pp-footnote'});
   if(!deck.cards.length)root.createEl('p',{text:'这个范围没有卡片。可以新建卡片，或从知识提炼中制卡。',cls:'pp-empty'});
   const create=root.createEl('details',{cls:'pp-create-box'});create.createEl('summary',{text:'怎样创建一张卡片？'});const sample=create.createDiv({cls:'pp-qa-example'});sample.createEl('span',{text:'正面 · 问题',cls:'pp-face-label'});sample.createEl('p',{text:'栈的出入顺序是什么？'});sample.createEl('span',{text:'背面 · 答案',cls:'pp-face-label'});sample.createEl('p',{text:'后进先出（LIFO）。最后入栈的元素最先出栈。'});

  }
  const warnings=[...this.scanWarnings,...notes.flatMap(n=>n.warnings.map(w=>n.path+' · '+w)),...deck.warnings];if(warnings.length){const detail=root.createEl('details',{cls:'pp-warnings'});detail.createEl('summary',{text:`${warnings.length} 条内容提示`});for(const w of warnings)detail.createEl('p',{text:w});}
 }

 private knowledgeMemo:{notes:NoteIndex[];key:string;result:ReturnType<typeof uniqueKnowledge>}|null=null;
 private knowledge(){const key=JSON.stringify([this.studyScope,this.host.currentPath]);if(this.knowledgeMemo?.notes===this.notes&&this.knowledgeMemo.key===key)return this.knowledgeMemo.result;const result=uniqueKnowledge(this.selectedNotes().flatMap(n=>n.knowledge||[]));this.knowledgeMemo={notes:this.notes,key,result};return result;}
 private renderKnowledge(root:HTMLElement){
  if(this.scanWarnings.length){const detail=root.createEl('details',{cls:'pp-warnings'});detail.createEl('summary',{text:`${this.scanWarnings.length} 条扫描提示`});for(const warning of this.scanWarnings)detail.createEl('p',{text:warning});}const found=this.knowledge(),visiblePool=found.points.filter(p=>this.knowledgeKind==='all'||this.knowledgeKind==='structured'&&p.confidence==='structured'||p.kind===this.knowledgeKind),intro=root.createDiv({cls:'pp-mode-intro'});
  intro.createEl('h2',{text:'从笔记里，发现值得记住的内容'});
  intro.createEl('p',{text:'先看定义与要点，核对原文后制成卡片。'});
  const count=root.createDiv({cls:'pp-study-stats'});for(const[n,label]of [[this.selectedNotes().length,'篇笔记'],[visiblePool.length,'条候选']]as[number,string][]){const item=count.createDiv();item.createEl('strong',{text:String(n)});item.createEl('span',{text:label});}
  if(found.duplicates)root.createEl('p',{text:`已折叠 ${found.duplicates} 条内容相同的候选，保留第一处来源`,cls:'pp-footnote'});
  const search=root.createEl('input',{cls:'pp-search',attr:{type:'search','aria-label':'搜索知识候选',placeholder:'搜索内容、标题或来源'}});search.value=this.knowledgeQuery;
  const filters=root.createDiv({cls:'pp-knowledge-filters'});const kind=filters.createEl('select',{attr:{'aria-label':'候选类型'}});for(const[value,label]of [['structured','定义与要点'],['all','全部（含原文段落）'],['definition','定义'],['list','要点列表'],['explanation','原文段落']])kind.createEl('option',{text:label,attr:{value}});kind.value=this.knowledgeKind;const hide=filters.createEl('label');const toggle=hide.createEl('input',{attr:{type:'checkbox'}});toggle.checked=this.hideSaved;hide.createEl('span',{text:'隐藏已制卡'});
  const actions=root.createDiv({cls:'pp-actions'});const review=this.button(actions,`核对所选 ${this.selectedCandidates.size} 条`,()=>{this.batch=[...this.selectedCandidates.values()];this.screen='batch';this.render();},true);review.disabled=!this.selectedCandidates.size;this.button(actions,'清空选择',()=>{this.selectedCandidates.clear();this.render();});
  const list=root.createDiv({cls:'pp-knowledge-list'});
  let previewCleanups:Array<()=>void>=[];const draw=()=>{for(const cleanup of previewCleanups)cleanup();previewCleanups=[];list.empty();const saved=new Set((this.host.store?.cards||[]).filter(c=>c.sourceRef).map(c=>c.sourcePath+'\n'+c.sourceRef!.fingerprint));const points=found.points.filter(p=>matchesQuery([p.question,p.excerpt,p.path],this.knowledgeQuery)&&(this.knowledgeKind==='all'||this.knowledgeKind==='structured'&&p.confidence==='structured'||p.kind===this.knowledgeKind)&&(!this.hideSaved||!saved.has(p.path+'\n'+p.fingerprint))).sort((a,b)=>({definition:0,list:1,explanation:2}[a.kind]-{definition:0,list:1,explanation:2}[b.kind]));const page=paginate(points,this.knowledgePage);this.knowledgePage=page.page;
   list.createEl('p',{text:`${points.length} 条匹配候选 · ${this.hideSaved?'隐藏已保存内容':'包含已保存内容'}`,cls:'pp-footnote'});
   for(const p of page.items){const item=list.createDiv({cls:'pp-knowledge-item'});const choose=item.createEl('label',{cls:'pp-select-candidate'});const check=choose.createEl('input',{attr:{type:'checkbox','aria-label':'选择候选：'+p.question}});check.checked=this.selectedCandidates.has(p.id);choose.createEl('span',{text:'选择'});check.addEventListener('change',()=>{if(check.checked){if(this.selectedCandidates.size>=100){check.checked=false;new Notice('每批最多 100 条，请先核对保存');return;}this.selectedCandidates.set(p.id,p);}else this.selectedCandidates.delete(p.id);review.textContent=`核对所选 ${this.selectedCandidates.size} 条`;review.disabled=!this.selectedCandidates.size;});item.createEl('span',{text:p.kind==='definition'?'定义候选 · 待核对':p.kind==='list'?'要点候选 · 待核对':'原文段落 · 待判断',cls:'pp-candidate-label'});const question=item.createDiv({cls:'pp-candidate-question'});previewCleanups.push(this.previews.mount(question,p.question,p.path));const answer=item.createDiv({cls:'pp-item-preview pp-candidate-excerpt'});previewCleanups.push(this.previews.mount(answer,p.excerpt,p.path));item.createEl('p',{text:`${p.path} · 第 ${p.line+1} 行`,cls:'pp-source-path'});this.button(item,'预览与编辑',()=>{this.candidate=p;this.candidateEditing=false;this.clozeTerm='';this.draft={front:p.question,back:p.excerpt,sourcePath:p.path};this.screen='candidate';this.render();});}
   this.pager(list,page,change=>{this.knowledgePage=change;draw();});
   if(!points.length)list.createEl('p',{text:'这个范围暂未找到可提炼的内容。规则会跳过代码、导航、表格、图片和过短文字；可切换范围，或手动从段落制卡。',cls:'pp-empty'});
  };search.addEventListener('input',()=>{this.knowledgeQuery=search.value;this.knowledgePage=0;draw();});kind.addEventListener('change',()=>{this.knowledgeKind=kind.value;this.knowledgePage=0;this.remember();this.render();});toggle.addEventListener('change',()=>{this.hideSaved=toggle.checked;this.knowledgePage=0;this.remember();draw();});draw();
 }
 private renderCandidate(root:HTMLElement){const p=this.candidate!;
  root.createEl('h2',{text:'先核对，再留下',cls:'pp-stage-title'});root.createEl('p',{text:p.reason+'。请结合上下文核对。',cls:'pp-muted'});
  const evidence=root.createDiv({cls:'pp-source-evidence'});evidence.createEl('span',{text:'逐字原文 · '+(p.headingPath.join(' › ')||p.heading),cls:'pp-face-label'});this.previews.mount(evidence,p.excerpt,p.path);this.button(evidence,`打开来源 · 第 ${p.line+1} 行`,()=>void this.openKnowledgeSource(p));const context=evidence.createEl('details',{cls:'pp-context'});context.createEl('summary',{text:'展开附近上下文'});this.previews.mount(context,p.context,p.path);context.createEl('span',{text:`从第 ${p.contextLine+1} 行开始 · 包含候选前后最多约 6 行`,cls:'pp-footnote'});for(const caveat of p.caveats||[])root.createEl('p',{text:caveat,cls:'pp-caveat'});
  const cloze=root.createEl('details',{cls:'pp-cloze-editor'});cloze.createEl('summary',{text:'也可以：把关键词挖空'});cloze.createEl('p',{text:'明确选择关键词，生成后再核对。只挖普通正文；不会挖代码或公式。重复出现的同词全部遮住。',cls:'pp-footnote'});const term=cloze.createEl('input',{cls:'pp-search',attr:{type:'text','aria-label':'要挖空的关键词',placeholder:'复制原文中的一个关键词',maxlength:'80'}});term.value=this.clozeTerm;term.addEventListener('input',()=>this.clozeTerm=term.value);const suggestions=keywordSuggestions(p.excerpt);if(suggestions.length){const options=cloze.createDiv({cls:'pp-actions'});for(const word of suggestions)this.button(options,word,()=>{this.clozeTerm=word;term.value=word;});}this.button(cloze,'生成挖空草稿',()=>{try{const draft=makeCloze(this.draft.back,this.clozeTerm,p.heading);this.draft={front:draft.front,back:draft.back,sourcePath:p.path};this.message=`已生成 ${draft.matches} 处挖空，请核对后保存`;this.render();}catch(e){this.message=(e as Error).message;this.render();}});
  const draft=root.createDiv({cls:'pp-candidate-draft'});const modes=draft.createDiv({cls:'pp-actions'});this.button(modes,this.candidateEditing?'切换到 Markdown 预览':'编辑 Markdown 源码',()=>{this.candidateEditing=!this.candidateEditing;this.render();});
  draft.createEl('p',{text:this.candidateEditing?'编辑模式 · 输入 Markdown 源码，切换预览核对排版':'预览模式 · 保存内容与下方预览一致',cls:'pp-footnote'});
  if(this.candidateEditing){this.field(draft,'候选问题',this.draft.front,v=>this.draft.front=v,'改成能独立理解的问题',4000);this.field(draft,'候选答案',this.draft.back,v=>this.draft.back=v,'保留必要上下文');}
  else{for(const [label,value]of [['候选问题',this.draft.front],['候选答案',this.draft.back]]){const face=draft.createDiv({cls:'pp-candidate-face'});face.createEl('h3',{text:label});this.previews.mount(face,value,p.path);}}
  root.createEl('p',{text:'请核对问题、答案和上下文，再确认保存。',cls:'pp-footnote'});
  this.button(root,'确认保存为卡片',()=>{const d={...this.draft};void this.run(async()=>{const current=await this.validateCandidate(p);if(!this.host.store)throw new Error(this.host.storageError);const outcome=await this.host.store.addMany([{...d,sourceRef:this.sourceRef(current.point)}],Date.now(),()=>this.assertSources([current]),this.selectedDeck||DEFAULT_DECK);if(!outcome.added)throw new Error('相同问题与答案的卡片已存在，没有重复保存。请返回问答卡片查看。');},()=>{this.selectedCandidates.delete(p.id);const saved=this.host.store!.cards.find(c=>c.front===d.front.trim()&&c.back===d.back.trim()&&c.sourcePath===d.sourcePath);if(saved)this.startCards([saved]);this.message='已保存 1 张卡片，开始回忆';});},true).addClass('pp-wide');
 }


 private invalidateBackup(){this.importPlan=null;this.previewedBackupText='';this.contentEl.querySelector('.pp-import-preview')?.remove();}
 private renderBackup(root:HTMLElement){
  root.createEl('h2',{text:'给学习进度留一份备份',cls:'pp-stage-title'});root.createEl('p',{text:'包括全部本地卡片、已记录的标记卡片评分和来源证据。备份包含你的问题与答案，请像笔记一样保管。',cls:'pp-muted'});
  this.button(root,'导出 JSON 到本地知识库',()=>void this.run(async()=>{const parts=exportBackupParts(this.host.store!.data),folder='Passage Practice backups';if(!this.app.vault.getAbstractFileByPath(folder))await this.app.vault.createFolder(folder);const stamp=new Date().toISOString().replace(/[:.]/g,'-'),paths:string[]=[];try{for(let i=0;i<parts.length;i++){const suffix=parts.length>1?`-part-${i+1}-of-${parts.length}`:'';let path=`${folder}/progress-${stamp}${suffix}.json`,n=1;while(this.app.vault.getAbstractFileByPath(path))path=`${folder}/progress-${stamp}-${n++}${suffix}.json`;await this.app.vault.create(path,parts[i]);paths.push(path);}}catch(error){throw new Error(`备份写入中断，已写 ${paths.length} / ${parts.length} 卷；这不是完整备份，请保留源数据并重新导出。`);}this.message=parts.length===1?'已保存备份：'+paths[0]:`已保存全部 ${parts.length} 卷到 ${folder}；恢复时请逐卷导入，缺一卷就不完整`;},()=>{}),true);
  root.createEl('h3',{text:'恢复缺失的卡片',cls:'pp-list-heading'});root.createEl('p',{text:'先预览，再确认。仅合并本地缺少的卡片；同编号冲突和相同内容保留本地版本，不覆盖现有进度。',cls:'pp-footnote'});
  const file=root.createEl('input',{attr:{type:'file',accept:'.json,application/json','aria-label':'选择进度备份'}});file.addEventListener('change',()=>{const selected=file.files?.[0];if(!selected)return;this.invalidateBackup();if(selected.size>MAX_BACKUP_BYTES){this.message='备份超过 10 MiB';this.render();return;}void this.run(async()=>{this.backupText=await selected.text();this.importPlan=planImport(this.host.store!.data,parseBackup(this.backupText));this.previewedBackupText=this.backupText;},()=>{});});
  this.field(root,'或粘贴 JSON 备份',this.backupText,value=>{this.backupText=value;this.invalidateBackup();},'支持导出的备份或旧版插件 data.json',MAX_BACKUP_BYTES);
  this.button(root,'预览合并结果',()=>{try{this.importPlan=planImport(this.host.store!.data,parseBackup(this.backupText));this.previewedBackupText=this.backupText;this.message='';}catch(e){this.importPlan=null;this.message=(e as Error).message;}this.render();});
  const plan=this.importPlan;if(plan){const summary=root.createDiv({cls:'pp-import-preview'});summary.createEl('h3',{text:'合并预览'});if(plan.backupPart)summary.createEl('p',{text:`分卷 ${plan.backupPart.index} / ${plan.backupPart.total} · 请导入同一备份的全部分卷。重复导入不会重复卡片。`,cls:'pp-notice'});const memberships=(plan.deckMemberships||[]).reduce((n,d)=>n+d.cardIds.length,0);if(memberships)summary.createEl('p',{text:`恢复 ${memberships} 条缺失卡组关联，已有成员保留`});
 if(plan.savedSchedulingAlgorithm){const label=(v:string|undefined)=>v==='sm2-osr'?'Spaced Repetition · 按天':'FSRS · 记忆模型';summary.createEl('p',{text:`备份算法：${label(plan.savedSchedulingAlgorithm)}；本地算法：${label(plan.localSchedulingAlgorithm)}`});const select=summary.createEl('select',{attr:{'aria-label':'恢复后的复习算法'}});select.createEl('option',{text:'请选择恢复后的算法',attr:{value:''}});select.createEl('option',{text:'保留本地算法',attr:{value:'keep-local'}});select.createEl('option',{text:'使用备份算法',attr:{value:'use-backup'}});select.value=plan.algorithmChoice||'';select.addEventListener('change',()=>{this.importPlan=planImport(this.host.store!.data,plan.incoming,(select.value||undefined) as ImportAlgorithmChoice|undefined);this.render();});summary.createEl('p',{text:'只选择以后评分的算法；现有卡片到期与历史不重排。',cls:'pp-footnote'});}
 summary.createEl('p',{text:`新增 ${plan.add.length} 张 · 完全相同 ${plan.identical} 张 · 内容重复 ${plan.duplicates} 张 · 编号冲突 ${plan.conflicts.length} 张 · 新增卡组 ${plan.decks?.length||0} 个 · 卡组冲突 ${plan.deckConflicts?.length||0} 个`});if(plan.conflicts.length)summary.createEl('p',{text:'冲突保留本地版本：'+plan.conflicts.slice(0,20).join('、')+(plan.conflicts.length>20?'…':''),cls:'pp-footnote'});summary.createEl('p',{text:'新增卡片保留备份的原评分和到期时间。原文仍需对应笔记存在；此操作不恢复笔记文件。',cls:'pp-footnote'});let added=0;const accept=this.button(summary,`确认合并 ${plan.add.length} 张卡片`,()=>void this.run(async()=>{if(this.importPlan!==plan||this.backupText!==this.previewedBackupText)throw new Error('备份内容已变化，请重新预览');added=await this.host.store!.importBackup(plan);},()=>{this.importPlan=null;this.backupText='';this.message=`已恢复 ${added} 张卡片，现有卡片未覆盖`;}),true);accept.disabled=plan.requiresAlgorithmChoice||(!plan.add.length&&!plan.decks?.length&&!memberships&&plan.schedulingAlgorithm===plan.localSchedulingAlgorithm)||this.busy;}
 }
 private sourceRef(p:KnowledgePoint){return {line:p.line,endLine:p.endLine,heading:p.headingPath.join(' › ')||p.heading,excerpt:p.excerpt,fingerprint:p.fingerprint};}
 private renderBatch(root:HTMLElement){
  root.createEl('h2',{text:`核对 ${this.batch.length} 条候选`,cls:'pp-stage-title'});root.createEl('p',{text:'逐条展开查看完整原文和问题。不合适的候选可移除；问题需要改写时，请返回单条预览。确认后才一次性保存为快照卡片。',cls:'pp-muted'});
  for(const p of this.batch){const box=root.createEl('details',{cls:'pp-batch-item'});if(this.batch.filter(x=>x.question===p.question).length>1)box.createEl('p',{text:'本批有相同题目，原文可能包含不同条件；请分别核对或单条改写。',cls:'pp-caveat'});const summary=box.createEl('summary');this.previews.mount(summary,p.question,p.path);box.createEl('p',{text:p.path+' · 第 '+(p.line+1)+' 行',cls:'pp-source-path'});this.previews.mount(box,p.excerpt,p.path);this.button(box,'从本批移除',()=>{this.batch=this.batch.filter(x=>x.id!==p.id);this.selectedCandidates.delete(p.id);this.render();});}
  let outcome={added:0,duplicates:0};const save=this.button(root,`确认保存 ${this.batch.length} 张卡片`,()=>void this.run(async()=>{if(!this.host.store)throw new Error(this.host.storageError);const verified:SourceValidation[]=[];for(const p of this.batch)verified.push(await this.validateCandidate(p));outcome=await this.host.store.addMany(verified.map(({point:p})=>({front:p.question,back:p.excerpt,sourcePath:p.path,sourceRef:this.sourceRef(p)})),Date.now(),()=>this.assertSources(verified),this.selectedDeck||DEFAULT_DECK);},()=>{this.selectedCandidates.clear();this.batch=[];this.screen='home';this.message=`已保存 ${outcome.added} 张卡片${outcome.duplicates?'，跳过 '+outcome.duplicates+' 张已有卡片':''}`;}),true);save.addClass('pp-wide');save.disabled=!this.batch.length||this.busy;
 }
 private assertSources(sources:readonly SourceValidation[]){for(const source of sources)if(this.app.vault.getAbstractFileByPath(source.path)!==source.file||source.file.path!==source.path||source.file.stat.mtime!==source.mtime||source.file.stat.size!==source.size)throw new Error('来源在确认期间变化，本次未保存。请刷新并重新核对候选。');}
 private async validateCandidate(p:KnowledgePoint):Promise<SourceValidation>{const file=this.app.vault.getAbstractFileByPath(p.path);if(!(file instanceof TFile))throw new Error('来源笔记已移动或删除，请刷新候选');const snapshot:SourceValidation={point:p,file,path:p.path,mtime:file.stat.mtime,size:file.stat.size};const text=await this.app.vault.read(file);this.assertSources([snapshot]);if(fingerprint(text.replace(/\r\n/g,'\n'))!==p.sourceFingerprint)throw new Error('来源内容或上下文已变化，本次未保存。请刷新并重新核对候选。');const current=extractKnowledge(text,p.path).points.find(x=>x.id===p.id&&x.fingerprint===p.fingerprint&&x.excerpt===p.excerpt);if(!current)throw new Error('来源内容已变化，本次未保存。请刷新并重新核对候选。');return{...snapshot,point:current};}
 private async openKnowledgeSource(p:KnowledgePoint){const f=this.app.vault.getAbstractFileByPath(p.path);if(!(f instanceof TFile)){new Notice('来源笔记已移动或删除');return;}await this.app.workspace.getLeaf(false).openFile(f,{eState:{line:p.line}});}
 private pager(root:HTMLElement,page:{page:number;pages:number;total:number},change:(page:number)=>void){const bar=root.createDiv({cls:'pp-pagination'});const prev=this.button(bar,'上一页',()=>change(page.page-1));prev.disabled=page.page===0;bar.createEl('span',{text:`${page.page+1} / ${page.pages} · ${page.total} 条`});const next=this.button(bar,'下一页',()=>change(page.page+1));next.disabled=page.page+1>=page.pages;}
 private currentEditor():MarkdownView|null{return this.host.activeEditor();}
 private selection(){const view=this.currentEditor();if(!view){new Notice('请先打开可编辑的笔记');return;}const editor=view.editor,text=editor.getSelection();if(!text.trim()||editor.listSelections().length!==1||text.length>50000){new Notice('请在笔记中选择一段连续文字，最多 50,000 字符');return;}this.passageQueue=[];this.beginPassage({text,question:view.file!.basename,line:editor.getCursor('from').line,path:view.file!.path,kind:'selection',sourceRef:selectionSourceRef(editor.getValue(),text,view.file!.path,editor.getCursor('from').line)});}
 startSelection(p:Passage){if(this.screen!=='home'){new Notice('请先返回学习，再开始新练习');return;}this.mode='passage';this.passageQueue=[];this.beginPassage(p);}
 private focusRecall(){this.contentEl.scrollTop=0;this.contentEl.querySelector<HTMLTextAreaElement>('textarea')?.focus({preventScroll:true});}
 private outlineBranches(note:NoteIndex){return note.outline.filter(b=>{const root=b.id===JSON.stringify(['outline',note.path,'document',0]);return !(root&&b.children.length===1&&b.children[0].kind==='heading');});}
 private saveLocation(mode:'passage'|'outline',item:Passage|OutlineBranch){if(!this.host.locations||('text' in item&&(!item.kind||item.kind==='selection')))return;const note=this.notes.find(n=>n.path===item.path);if(!note?.sourceFingerprint)return;const location:PracticeLocation={mode,path:item.path,line:item.line,identity:'text' in item?fingerprint(item.question+'\n'+item.text):item.id,sourceFingerprint:note.sourceFingerprint,scope:{...this.studyScope},currentPath:this.host.currentPath,excludedPaths:[...this.excludedPaths]};void this.host.locations.save(location).catch(()=>{this.message='练习位置未能保存；卡片进度不受影响，可重试开始本题';if(!this.closed)this.render();});}
 private renderResume(root:HTMLElement,mode:'passage'|'outline'){const saved=this.host.locations?.get(mode);if(!saved)return;const matching=JSON.stringify(saved.scope)===JSON.stringify(this.studyScope)&&JSON.stringify(saved.excludedPaths)===JSON.stringify(this.excludedPaths)&&(this.studyScope.kind!=='current'||saved.currentPath===this.host.currentPath);if(!matching)return;this.button(root,mode==='passage'?'继续上次小节':'继续上次大纲节点',()=>void this.run(async()=>{if(!await this.refresh(true))throw new Error('刷新未完成，未恢复练习');const note=this.selectedNotes().find(n=>n.path===saved.path);if(!note||note.sourceFingerprint!==saved.sourceFingerprint)throw new Error('上次来源已变化或不在当前范围，请重新选择练习');if(mode==='passage'){const queue=this.selectedNotes().flatMap(n=>n.passages),at=queue.findIndex(p=>p.path===saved.path&&p.line===saved.line&&fingerprint(p.question+'\n'+p.text)===saved.identity);if(at<0)throw new Error('上次小节已变化，请重新选择');const session=sessionFrom(queue,queue[at],this.reviewOrder);this.passageQueue=session.queue;this.passagePosition=session.position;this.beginPassage(queue[at]);}else{const queue=this.selectedNotes().flatMap(n=>this.outlineBranches(n)),at=queue.findIndex(b=>b.id===saved.identity);if(at<0)throw new Error('上次大纲节点已变化，请重新选择');const session=sessionFrom(queue,queue[at],this.reviewOrder);this.outlineQueue=session.queue;this.outlinePosition=session.position;this.outlineHistory=[];this.beginOutline(queue[at]);}},()=>{}));}
 private beginPassage(p:Passage,reset=false){if(this.passage&&this.session)this.passageDrafts.set(this.passage,{session:this.session,saved:this.passageSaved});this.message='';this.passage=p;const cached=reset?undefined:this.passageDrafts.get(p);this.session=cached?.session||new Session(p.text,p.question);if(!cached&&p.kind&&p.kind!=='selection')this.session.start(p.question);this.passageSaved=cached?.saved||false;this.screen='passage';this.host.shield(this.session.stage==='recall'&&this.visible());this.saveLocation('passage',p);this.render();this.focusRecall();}
 private renderPassage(root:HTMLElement){const s=this.session!,p=this.passage!;const nav=root.createDiv({cls:'pp-practice-nav'});nav.createEl('span',{text:this.passageQueue.length?`第 ${this.passagePosition+1} / ${this.passageQueue.length} 节`:'选段练习'});if(this.passageQueue.length){const previous=this.button(nav,'上一节',()=>{if(this.session!==s||this.passagePosition<=0)return;this.passagePosition--;this.beginPassage(this.passageQueue[this.passagePosition]);});previous.disabled=this.busy||this.passagePosition===0;const next=this.button(nav,'下一节',()=>{if(this.session!==s||this.passagePosition+1>=this.passageQueue.length)return;this.passagePosition++;this.beginPassage(this.passageQueue[this.passagePosition]);});next.disabled=this.busy||this.passagePosition+1>=this.passageQueue.length;}root.createEl('p',{text:p.path,cls:'pp-source-path'});if(p.headingPath?.length)root.createEl('p',{text:p.headingPath.join(' › '),cls:'pp-heading-path'});if(p.kind&&p.kind!=='selection')root.createEl('p',{text:p.kind==='intro'?'父标题引言 · 仅子标题前的正文':p.kind==='preamble'?'笔记引言 · 首个标题前的正文':p.kind==='document'?'无 Markdown 标题 · 全文作为一个答案':'标题小节 · 含本节全部正文',cls:'pp-footnote'});root.createEl('h2',{text:s.stage==='question'?'01 · 阅读与准备':s.stage==='recall'?'02 · 不看原文，试着回忆':'03 · 对照与漏点',cls:'pp-stage-title'});
  if(s.stage==='question'){const source=root.createDiv({cls:'pp-reading'});source.createEl('span',{text:'原文 · 本次对照答案',cls:'pp-face-label'});this.previews.mount(source,s.source,p.path);this.field(root,'自问的问题',s.question,v=>s.question=v,'用一个问题概括这段内容',4000);this.button(root,'遮住原文，开始回忆',()=>{s.start(s.question);this.host.shield(true);this.render();},true).addClass('pp-wide');root.createEl('p',{text:'回忆时暂时遮住工作区的笔记内容；揭晓或返回后恢复。',cls:'pp-footnote'});}
  else if(s.stage==='recall'){root.createEl('p',{text:s.question,cls:'pp-question'});this.field(root,'我的回忆',s.recall,v=>s.recall=v,'用自己的话写下记得的内容……');this.button(root,'揭晓并对照',()=>{if(this.session!==s||s.stage!=='recall')return;s.reveal();this.host.shield(false);this.render();void this.revealSource(p,()=>this.screen==='passage'&&this.session===s&&s.stage==='compare');},true).addClass('pp-wide');root.createEl('p',{text:'想不起来也可以揭晓。',cls:'pp-footnote'});}
  else{root.createEl('p',{text:s.question,cls:'pp-question'});mountComparison(root.createDiv(),s.target,s.recall,s.rounds.length?'本轮漏点答案':p.kind&&p.kind!=='selection'?'本节完整答案':'原始选段',this.compare,value=>this.compare=value,(parent,text,onReady)=>this.previews.mount(parent,text,p.path,onReady));let retry:HTMLButtonElement;this.field(root,'我漏掉的要点（每行一条）',s.missed,v=>{s.missed=v;retry.disabled=!s.points().length;},'自己判断漏掉了哪些要点');const actions=root.createDiv({cls:'pp-actions'});retry=this.button(actions,'只练这些漏点',()=>{if(s.retry()){this.host.shield(true);this.render();}},true);retry.disabled=!s.points().length||this.busy;
   const save=this.button(actions,this.passageSaved?'复习记录已保存':'保存新复习记录',()=>void this.run(()=>createReview((path,text)=>this.app.vault.create(path,text),path=>!!this.app.vault.getAbstractFileByPath(path),reviewNote(s,p.path,new Date().toISOString())),()=>{this.passageSaved=true;this.message='已新建复习记录，原笔记未改动';}));save.disabled=this.passageSaved||this.busy;
   this.button(actions,'把漏点制成卡片',()=>this.openEditor(undefined,false,{front:s.question,back:s.points().join('\n')||s.target,sourcePath:p.path,sourceRef:passageSourceRef(p)}));
   this.button(actions,p.kind&&p.kind!=='selection'?'重新回忆本节':'重新练习选段',()=>{if(this.session===s)this.beginPassage(p,true);});
   this.button(actions,'把本节制成卡片',()=>this.openEditor(undefined,false,{front:p.question,back:p.text,sourcePath:p.path,sourceRef:passageSourceRef(p)}));
  }
 }
 private renderOutlineHome(root:HTMLElement){
  const notes=this.selectedNotes(),branches=notes.flatMap(n=>this.outlineBranches(n)),stats=root.createDiv({cls:'pp-study-stats'});
  for(const[count,label]of [[notes.length,'篇笔记'],[branches.length,'个分支题']]as const){const tile=stats.createDiv();tile.createEl('strong',{text:String(count)});tile.createEl('span',{text:label});}
  const intro=root.createDiv({cls:'pp-mode-intro'});intro.createEl('h2',{text:'看父节点，回忆子分支'});intro.createEl('p',{text:'支持 Markdown 标题树和缩进列表，只有关键词也能练。先回想直属子节点，再逐项揭晓、继续深入下一层。'});
  root.createEl('p',{text:'这里复习已有结构，不自动概括正文；XMind 文件和图片思维导图暂不解析。',cls:'pp-footnote'});
  this.button(root,'刷新内容',()=>void this.refresh(true));
  const warnings=[...this.scanWarnings,...notes.flatMap(n=>n.warnings.map(w=>n.path+' · '+w))];if(warnings.length){const details=root.createEl('details',{cls:'pp-warnings'});details.createEl('summary',{text:`${warnings.length} 条结构提示`});for(const warning of warnings)details.createEl('p',{text:warning});}
  if(!branches.length){root.createEl('p',{text:'这个范围没有标题树或列表分支。可使用多级标题，或「- 父节点」下缩进列出子节点。',cls:'pp-empty'});return;}
  const search=root.createEl('input',{cls:'pp-search',attr:{type:'search','aria-label':'搜索大纲节点',placeholder:'搜索父节点、标题路径或笔记路径'}});search.value=this.outlineQuery;const list=root.createDiv({cls:'pp-passage-list'});
  const draw=()=>{list.empty();const filtered=branches.filter(p=>matchesQuery([p.label,p.path,p.ancestorPath.join(' ')],this.outlineQuery)),page=paginate(filtered,this.outlinePage);this.outlinePage=page.page;
   for(const p of page.items){const button=this.button(list,'',()=>{const session=sessionFrom(filtered,p,this.reviewOrder);this.outlineQueue=session.queue;this.outlinePosition=session.position;this.outlineHistory=[];this.beginOutline(p);});button.addClass('pp-outline-choice');button.createEl('span',{text:p.label,cls:'pp-item-title'});button.createEl('span',{text:p.ancestorPath.join(' › '),cls:'pp-item-preview'});button.createEl('span',{text:`${p.children.length} 个直属子节点 · 答案尚未揭晓`,cls:'pp-footnote'});button.createEl('span',{text:p.path,cls:'pp-source-path'});}
   this.pager(list,page,change=>{this.outlinePage=change;draw();});};search.addEventListener('input',()=>{this.outlineQuery=search.value;this.outlinePage=0;draw();});draw();
 }
 private beginOutline(branch:OutlineBranch){this.outline=branch;this.outlineRevealed=0;this.outlineRecall='';this.screen='outline';this.host.shield(this.visible());this.saveLocation('outline',branch);this.render();this.focusRecall();}
 private renderOutline(root:HTMLElement){
  const branch=this.outline!,complete=this.outlineRevealed>=branch.children.length;
  root.createEl('p',{text:branch.path,cls:'pp-source-path'});if(branch.ancestorPath.length)root.createEl('p',{text:branch.ancestorPath.join(' › '),cls:'pp-heading-path'});
  root.createEl('h2',{text:'它有哪些子分支？',cls:'pp-stage-title'});const parent=root.createDiv({cls:'pp-outline-parent'});parent.createEl('span',{text:'父节点 · 本轮提示',cls:'pp-face-label'});parent.createEl('p',{text:branch.label,cls:'pp-question'});
  root.createEl('p',{text:`已揭晓 ${Math.min(this.outlineRevealed,branch.children.length)} / ${branch.children.length} 个直属子节点`,cls:'pp-progress',attr:{role:'status'}});
  if(!complete)this.field(root,'我记得的分支（可选）',this.outlineRecall,value=>this.outlineRecall=value,'可以只写关键词，每行一个……');else if(this.outlineRecall){const recall=root.createDiv({cls:'pp-reading'});recall.createEl('span',{text:'我的回忆',cls:'pp-face-label'});this.previews.mount(recall,this.outlineRecall,branch.path);}
  const tree=root.createEl('ol',{cls:'pp-outline-tree','attr':{'aria-label':'本轮子分支'}});
  branch.children.forEach((node,index)=>{const item=tree.createEl('li',{cls:index<this.outlineRevealed?'is-revealed':'is-hidden'});
   if(index>=this.outlineRevealed){item.createEl('span',{text:'尚未揭晓',cls:'pp-outline-placeholder'});return;}
   item.createEl('span',{text:node.label,cls:'pp-outline-node'});
   if(node.children.length){const child:OutlineBranch={id:node.id,label:node.label,line:node.line,path:node.path,headingPath:node.kind==='heading'?[...branch.headingPath,node.label]:[...branch.headingPath],ancestorPath:[...branch.ancestorPath,node.label],children:node.children};this.button(item,`继续回忆下一级（${node.children.length}）`,()=>{if(this.outline!==branch)return;this.outlineHistory.push(branch);this.beginOutline(child);});}
  });
  const actions=root.createDiv({cls:'pp-actions'});
  if(!complete){this.button(actions,'揭晓下一个分支',()=>{if(this.outline!==branch)return;this.outlineRevealed++;this.host.shield(this.outlineRevealed<branch.children.length&&this.visible());this.render();},true);this.button(actions,'全部揭晓',()=>{if(this.outline!==branch)return;this.outlineRevealed=branch.children.length;this.host.shield(false);this.render();});}
  else this.button(actions,'重新回忆本节点',()=>{if(this.outline===branch)this.beginOutline(branch);},true);
  if(this.outlineHistory.length)this.button(actions,'返回上一级节点',()=>{if(this.outline===branch)this.beginOutline(this.outlineHistory.pop()!);});
  if(complete&&this.outlineQueue.length>this.outlinePosition+1)this.button(actions,'下一分支题',()=>{if(this.outline!==branch)return;this.outlinePosition++;this.outlineHistory=[];this.beginOutline(this.outlineQueue[this.outlinePosition]);});
  root.createEl('p',{text:complete?'核对后可继续深入下一层。':'先回想，再逐项揭晓。',cls:'pp-footnote'});
 }
 private startCards(cards:Card[]){this.againCandidates.clear();this.repeatPass=false;this.queue=sessionOrder(cards,this.reviewOrder);this.reviewed=0;this.sessionTotal=cards.length;this.undo=undefined;this.screen='card';this.advance();}
 private advance(){if(!this.queue.length&&this.retryAgain&&!this.repeatPass){this.repeatPass=true;const now=Date.now();this.queue=[...this.againCandidates].map(id=>this.host.store?.get(id)).filter((c):c is Card=>!!c&&!c.suspended&&c.dueAt<=now);this.sessionTotal+=this.queue.length;}this.current=this.queue[0];this.revealed=false;this.recall='';this.host.shield(!!this.current&&this.visible());this.render();this.focusRecall();}
 private renderCard(root:HTMLElement){const c=this.current;root.createEl('p',{text:`本轮已完成 ${this.reviewed} / ${this.sessionTotal}${this.repeatPass?' · 再练最多一次':''}`,cls:'pp-progress'});
  if(!c){root.createEl('h2',{text:'这一轮，完成了',cls:'pp-stage-title'});root.createEl('p',{text:`已保存 ${this.reviewed} 次评分，下次复习已安排。`,cls:'pp-muted'});const upcoming=this.cards().cards.filter(c=>!c.suspended).sort((a,b)=>a.dueAt-b.dueAt)[0];if(upcoming)root.createEl('p',{text:upcoming.dueAt<=Date.now()?'还有卡片到期，可返回开始新一轮':`下次到期 ${date(upcoming.dueAt)}`,cls:'pp-footnote'});this.undoButton(root);this.button(root,'返回学习范围',()=>this.home(),true);return;}
  if((this.host.store?.schedulingAlgorithm??'fsrs')==='sm2-osr')root.createEl('p',{text:'按天复习 · 忘了会在今天到期，本轮结束后可再练',cls:'pp-footnote'});if(activeAlgorithm(c)!==(this.host.store?.schedulingAlgorithm??'fsrs'))root.createEl('p',{text:'本次评分将初始化所选算法，之前的复习历史保留',cls:'pp-footnote'});
  root.createEl('p',{text:c.sourcePath||'本地快照 · 无来源笔记',cls:'pp-source-path'});if(c.id.startsWith('note:')&&!this.notes.some(n=>n.cards.some(x=>x.id===c.id)))root.createEl('p',{text:'来源标记缺失：本次使用已保存的最后快照，评分继续独立保存。',cls:'pp-footnote'});const front=root.createDiv({cls:'pp-front'});front.createEl('span',{text:'正面 · 问题',cls:'pp-face-label'});this.previews.mount(front,c.front,c.sourcePath);
  if(!this.revealed){this.field(root,'我的回忆（可选）',this.recall,v=>this.recall=v,'可以默想，也可以写下来……');this.button(root,'翻到背面 · 揭晓答案',()=>{if(this.current!==c||this.revealed)return;this.revealed=true;this.host.shield(false);this.render();if(c.sourcePath)void this.revealSource(c,()=>this.screen==='card'&&this.current===c&&this.revealed);},true).addClass('pp-wide');this.undoButton(root);root.createEl('p',{text:'退出不会记录评分。',cls:'pp-footnote'});}
  else{const back=root.createDiv({cls:'pp-flash-answer'});back.createEl('h2',{text:'背面 · 答案'});this.previews.mount(back,c.back,c.sourcePath);if(this.recall){const own=root.createDiv({cls:'pp-own-recall'});own.createEl('h2',{text:'我的回忆'});this.previews.mount(own,this.recall,c.sourcePath);}
   const corrections=root.createDiv({cls:'pp-actions'});if(!c.id.startsWith('note:'))this.button(corrections,'就地修改卡片',()=>this.openEditor(c));else this.button(corrections,'打开笔记修改',()=>void this.openSource(c));this.button(corrections,'暂停并跳过',()=>void this.run(()=>c.id.startsWith('note:')?this.host.store!.setAuthoredSuspended(c,true):this.host.store!.suspend(c.id,c.revision,true),()=>{this.queue.shift();this.sessionTotal=Math.max(this.reviewed,this.sessionTotal-1);this.undo=undefined;this.advance();}));
   const ratings=root.createDiv({cls:'pp-ratings'}),now=Date.now();for(const rating of ['again','hard','good','easy']as Rating[]){const next=applyRating(c,rating,now,this.host.store?.schedulingAlgorithm??'fsrs',srHistogram(this.host.store?.cards??[],now)),interval=next.sr?(next.intervalDays===0?'今天':`${next.intervalDays} 天`):intervalLabel(next.dueAt,now);const b=this.button(ratings,'',()=>void this.rate(c,rating),rating==='good');b.setAttribute('aria-label',`${ratingLabels[rating]} · ${interval}${next.sr&&next.intervalDays===0?'':'后'}`);b.createEl('strong',{text:ratingLabels[rating]});b.createEl('span',{text:`${interval}${next.sr&&next.intervalDays===0?'':'后'}`});}
   root.createEl('p',{text:'选择后保存进度并继续下一张。',cls:'pp-footnote'});
  }
 }
 private assertIndexCurrent(indexedFiles:readonly {file:TFile;path:string;mtime:number;size:number}[],exclusions:readonly string[]){const files=this.app.vault.getMarkdownFiles().filter(f=>!excluded(f.path,['Passage Practice','Passage Practice backups',...exclusions])),set=new Set(files);if(files.length!==indexedFiles.length||indexedFiles.some(x=>!set.has(x.file)||x.file.path!==x.path||x.file.stat.mtime!==x.mtime||x.file.stat.size!==x.size))throw new Error('评分提交前笔记已变化，请刷新后重新复习');}
 private async rate(c:Card,rating:Rating){const before={queue:[...this.queue],reviewed:this.reviewed,total:this.sessionTotal,again:[...this.againCandidates],repeatPass:this.repeatPass};await this.run(async()=>{if(c.id.startsWith('note:')){if(!await this.refresh())throw new Error('内容刷新被中断，本次未评分，请返回后重新开始');const current=studyCards(this.notes,this.host.store!.cards,{kind:'all',value:''},'',Date.now()).cards.find(x=>x.id===c.id);if(!current||current.front!==c.front||current.back!==c.back||current.revision!==c.revision)throw new Error('来源卡片已修改、移除或编号重复。本次未评分，请返回学习并重新开始。');const verifiedFiles=this.indexedFiles.map(x=>({...x})),exclusions=[...this.excludedPaths];return this.host.store!.rateAuthored({...c,sourcePath:current.sourcePath},rating,Date.now(),()=>this.assertIndexCurrent(verifiedFiles,exclusions));}return this.host.store!.rate(c.id,c.revision,rating);},()=>{if(rating==='again'&&!this.repeatPass)this.againCandidates.add(c.id);else this.againCandidates.delete(c.id);this.undo={previous:c,revision:c.revision+1,...before};this.queue.shift();this.reviewed++;this.advance();});}
 private undoButton(root:HTMLElement){const undo=this.undo;if(!undo)return;this.button(root,'撤销上次评分',()=>void this.run(()=>this.host.store!.restoreRating(undo.previous,undo.revision),()=>{const restored=this.host.store!.get(undo.previous.id)!;this.queue=undo.queue.map(c=>c.id===restored.id?restored:c);this.reviewed=undo.reviewed;this.sessionTotal=undo.total;this.againCandidates=new Set(undo.again);this.repeatPass=undo.repeatPass;this.undo=undefined;this.advance();}));}
 openSeed(seed:CardSeed){if(this.screen!=='home'){new Notice('请先返回学习，再创建新卡片');return;}this.mode='cards';this.openEditor(undefined,false,seed);}
 private openEditor(card?:Card,insert=false,seed?:CardSeed){if(!this.host.store){new Notice(this.host.storageError);return;}this.returnScreen=this.screen==='library'?'library':this.screen==='card'?'card':this.screen==='passage'?'passage':'home';this.draft=seed?{...seed}:card?{front:card.front,back:card.back,sourcePath:card.sourcePath,sourceRef:card.sourceRef}:{front:'',back:'',sourcePath:''};this.editCard=card;this.clozeTerm='';this.relearn=false;this.insert=false;this.screen='edit';this.render();}
 private cancelEdit(){this.screen=this.returnScreen;this.message='';this.render();}
 private renderEditor(root:HTMLElement){root.createEl('h2',{text:this.editCard?'编辑卡片':'新建卡片',cls:'pp-stage-title'});root.createEl('p',{text:'修改原笔记后，已保存的卡片答案不会自动更新。',cls:'pp-muted'});this.field(root,'正面 · 问题',this.draft.front,v=>this.draft.front=v,'例如：栈的出入顺序是什么？',4000);this.field(root,'背面 · 答案',this.draft.back,v=>this.draft.back=v,'例如：后进先出（LIFO）。');root.createEl('p',{text:`来源：${this.draft.sourcePath||'无来源笔记'}`,cls:'pp-source-path'});
  if(!this.insert){const cloze=root.createEl('details',{cls:'pp-cloze-editor'});cloze.createEl('summary',{text:'把当前答案中的关键词挖空'});const term=cloze.createEl('input',{attr:{'aria-label':'要挖空的关键词',maxlength:'80',placeholder:'输入答案中原有的关键词'}});term.value=this.clozeTerm;term.addEventListener('input',()=>this.clozeTerm=term.value);this.button(cloze,'生成挖空草稿',()=>{try{const result=makeCloze(this.draft.back,this.clozeTerm,this.draft.front);this.draft.front=result.front;this.draft.back=result.back;this.message='已生成挖空草稿，请核对后保存';}catch(e){this.message=(e as Error).message;}this.render();});}
  if(this.editCard){const row=root.createEl('label',{cls:'pp-relearn'}),check=row.createEl('input',{attr:{type:'checkbox'}});check.checked=this.relearn;check.addEventListener('change',()=>this.relearn=check.checked);row.createEl('span',{text:'立即重新学习（到期设为现在，保留累计评分次数）'});}
  if(this.insert){const syntax=root.createEl('details',{cls:'pp-syntax'});syntax.createEl('summary',{text:'查看标记方式'});syntax.createEl('pre',{text:'```practice-card\nid: 自动生成，无需手写\n问题：\n这里是正面的问题\n答案：\n这里是背面的答案\n```'});syntax.createEl('p',{text:'保留 id，问题与答案可随时编辑。阅读视图会显示双面标签。复制卡片时请重新插入，避免重复编号。'});}
  this.button(root,'保存卡片',()=>{const d={...this.draft},c=this.editCard;if(!d.front.trim()||!d.back.trim()){this.message='请填写问题和答案';this.render();return;}let saved:Card|undefined;void this.run(async()=>{saved=c?await this.host.store!.edit(c.id,c.revision,d.front,d.back,Date.now(),this.relearn):await this.host.store!.add(d.front,d.back,d.sourcePath,Date.now(),this.selectedDeck||DEFAULT_DECK,d.sourceRef);},()=>{this.screen=this.returnScreen;if(saved){if(this.returnScreen==='card'&&c){this.queue=this.queue.map(x=>x.id===c.id?saved!:x);this.undo=undefined;this.advance();}else if(!c)this.startCards([saved]);}this.message='卡片已保存';void this.refresh(true);});},true).addClass('pp-wide');
 }
 private renderLibrary(root:HTMLElement){
  const pool=this.cards().cards;
  const known=new Set(this.notes.flatMap(n=>n.cards).map(c=>c.id)),orphaned=(this.host.store?.cards||[]).filter(c=>c.id.startsWith('note:')&&!known.has(c.id));if(orphaned.length)root.createEl('p',{text:`${orphaned.length} 条标记卡片记录不在当前索引，评分仍保留，不会自动删除。`,cls:'pp-footnote'});
  root.createEl('h2',{text:'这个范围的卡片',cls:'pp-stage-title'});this.renderScopeCount(root,pool.length);
  root.createEl('p',{text:'每批最多 1,000 张。更改搜索或筛选会清空选择；翻页保留选择。',cls:'pp-footnote'});
  const filters=root.createDiv({cls:'pp-card-filters'}),search=filters.createEl('input',{cls:'pp-search',attr:{type:'search','aria-label':'搜索卡片',placeholder:'搜索问题、答案或来源'}});search.value=this.query;
  const choose=(label:string,value:string,options:string[][],change:(v:string)=>void)=>{const wrap=filters.createEl('label');wrap.createEl('span',{text:label});const select=wrap.createEl('select',{attr:{'aria-label':label}});for(const[v,name]of options)select.createEl('option',{text:name,attr:{value:v}});select.value=value;select.addEventListener('change',()=>{change(select.value);this.selectedCards.clear();this.bulkReview=null;this.cardPage=0;draw();});return select;};
  choose('卡片状态',this.cardStatus,[['all','全部状态'],['active','复习中'],['due','已到期'],['scheduled','未到期'],['suspended','已暂停'],['new','尚未复习']],v=>this.cardStatus=v as CardStatus);
  choose('卡片类型',this.cardType,[['all','全部类型'],['snapshot','本地快照'],['authored','笔记标记']],v=>this.cardType=v as 'all'|'snapshot'|'authored');
  const sources=[...new Set(pool.map(c=>c.sourcePath))].sort();if(this.cardSource&&!sources.includes(this.cardSource===NO_SOURCE?'':this.cardSource)){this.cardSource='';this.selectedCards.clear();this.bulkReview=null;}choose('卡片来源',this.cardSource,[['','全部来源'],...sources.map(path=>[path||NO_SOURCE,path||'无来源笔记'])],v=>this.cardSource=v);
  const membership=root.createDiv({cls:'pp-actions'}),target=membership.createEl('select',{attr:{'aria-label':'加入卡组'}});for(const deck of this.host.store?.decks||[])target.createEl('option',{text:deck.name,attr:{value:deck.id}});this.button(membership,'将所选卡片加入卡组',()=>{const selected=[...this.selectedCards.values()];if(!selected.length){this.message='请先选择卡片';this.render();return;}void this.run(()=>this.host.store!.assignDeck(target.value,selected),()=>{this.selectedCards.clear();this.message='已保存卡组关联';});});
  const selectedDeck=this.host.store?.decks.find(d=>d.id===this.selectedDeck);if(selectedDeck)this.button(membership,'从当前卡组移出所选卡片',()=>{const selected=[...this.selectedCards.values()];if(!selected.length){this.message='请先选择卡片';this.render();return;}void this.run(()=>this.host.store!.removeFromDeck(selectedDeck.id,selectedDeck.revision,selected),()=>{this.selectedCards.clear();this.message='已移出当前卡组；卡片和评分保留，可在全部卡组中重新加入';});});
  const list=root.createDiv({cls:'pp-library'});
  const draw=()=>{list.empty();const cards=filterCards(this.cards().cards,{query:this.query,status:this.cardStatus,type:this.cardType,source:this.cardSource},Date.now()),allowed=new Map(cards.map(c=>[c.id,c]));
   for(const[id,c]of this.selectedCards)if(!allowed.has(id)||!sameCard(c,allowed.get(id)!)){this.selectedCards.delete(id);this.bulkReview=null;}
   const page=paginate(cards,this.cardPage);this.cardPage=page.page;
   list.createEl('p',{text:`${cards.length} 张匹配 · 已选 ${this.selectedCards.size} 张（跨页）`,cls:'pp-selection-count',attr:{role:'status'}});
   const selectItems=(items:readonly Card[])=>{if(items.length>1000){this.message='每批最多 1000 张，请缩小筛选范围';this.render();return;}for(const c of items){if(this.selectedCards.size>=1000&&!this.selectedCards.has(c.id)){this.message='每批最多 1000 张';break;}this.selectedCards.set(c.id,c);}this.bulkReview=null;draw();};
   const actions=list.createDiv({cls:'pp-actions'});this.button(actions,'全选本页',()=>selectItems(page.items)).disabled=!page.items.length||this.busy;this.button(actions,`选择全部匹配 ${cards.length} 张`,()=>selectItems(cards)).disabled=!cards.length||cards.length>1000||this.busy;this.button(actions,'清空选择',()=>{this.selectedCards.clear();this.bulkReview=null;draw();}).disabled=!this.selectedCards.size||this.busy;
   for(const[suspended,label]of [[true,'批量暂停'],[false,'批量恢复']]as const){const button=this.button(actions,label,()=>{const selected=[...this.selectedCards.values()].filter(c=>c.suspended!==suspended);this.bulkReview={cards:selected,suspended};draw();});button.disabled=![...this.selectedCards.values()].some(c=>c.suspended!==suspended)||this.busy;}
   const review=this.bulkReview;if(review){const confirm=list.createDiv({cls:'pp-bulk-confirm',attr:{role:'region','aria-label':'核对批量操作'}});confirm.createEl('h3',{text:`确认${review.suspended?'暂停':'恢复'} ${review.cards.length} 张？`});confirm.createEl('p',{text:'只处理下面列出的已选卡片；评分次数、间隔和到期时间保持原值。恢复后已到期的卡片会进入队列。'});const details=confirm.createEl('details');details.createEl('summary',{text:'查看全部操作对象与来源'});for(const c of review.cards)details.createEl('p',{text:`${c.front} · ${c.sourcePath||'无来源'}`});this.button(confirm,'取消批量操作',()=>{this.bulkReview=null;draw();});this.button(confirm,`确认${review.suspended?'暂停':'恢复'} ${review.cards.length} 张`,()=>void this.commitBulk(review),true);}
   for(const c of page.items){const item=list.createDiv({cls:'pp-library-card'}),selection=item.createEl('label',{cls:'pp-card-select'}),check=selection.createEl('input',{attr:{type:'checkbox','aria-label':'选择卡片：'+c.front}});check.checked=this.selectedCards.has(c.id);selection.createEl('span',{text:c.id.startsWith('note:')?'笔记标记卡片':'本地快照卡片'});check.addEventListener('change',()=>{if(this.busy)return;if(check.checked){if(this.selectedCards.size>=1000){check.checked=false;new Notice('每批最多 1000 张');return;}this.selectedCards.set(c.id,c);}else this.selectedCards.delete(c.id);this.bulkReview=null;draw();});
    item.createEl('h3',{text:c.front});item.createEl('p',{text:`${c.suspended?'已暂停':c.dueAt<=Date.now()?'已到期':'到期 '+date(c.dueAt)} · 复习 ${c.reviews} 次`,cls:'pp-muted'});item.createEl('p',{text:c.sourcePath||'无来源',cls:'pp-source-path'});const row=item.createDiv({cls:'pp-actions'});if(c.id.startsWith('note:'))this.button(row,'打开笔记修改',()=>void this.openSource(c));else{this.button(row,'编辑卡片',()=>this.openEditor(c));if(c.sourcePath)this.button(row,'打开来源',()=>void this.openSource(c));if(c.sourceRef){const status=item.createEl('p',{text:'可核对保存时的来源',cls:'pp-footnote'});this.button(row,'核对来源',()=>void this.checkEvidence(c,status));}}
    this.button(row,c.suspended?'恢复复习':'暂停复习',()=>void this.run(()=>c.id.startsWith('note:')?this.host.store!.setAuthoredSuspended(c,!c.suspended):this.host.store!.suspend(c.id,c.revision,!c.suspended),()=>{this.selectedCards.delete(c.id);this.bulkReview=null;}));
   }this.pager(list,page,change=>{this.cardPage=change;draw();});if(!cards.length)list.createEl('p',{text:'没有匹配的卡片。',cls:'pp-empty'});
  };
  search.addEventListener('input',()=>{this.query=search.value;this.cardPage=0;this.selectedCards.clear();this.bulkReview=null;draw();});draw();
 }
 private async commitBulk(review:{cards:Card[];suspended:boolean}){let changed=0;await this.run(async()=>{if(this.bulkReview!==review||!review.cards.length)throw new Error('选择已变化，请重新核对');const hasAuthored=review.cards.some(c=>c.id.startsWith('note:'));if(hasAuthored&&!await this.refresh(true))throw new Error('来源刷新被中断，本批未保存');const visible=filterCards(this.cards().cards,{query:this.query,status:this.cardStatus,type:this.cardType,source:this.cardSource},Date.now()),byId=new Map(visible.map(c=>[c.id,c]));for(const c of review.cards)if(!byId.has(c.id)||!sameCard(c,byId.get(c.id)!))throw new Error('所选卡片或筛选结果已变化，本批未保存，请重新核对');const files=this.indexedFiles.map(x=>({...x})),exclusions=[...this.excludedPaths];changed=await this.host.store!.suspendMany(review.cards,review.suspended,Date.now(),hasAuthored?()=>this.assertIndexCurrent(files,exclusions):undefined);},()=>{this.selectedCards.clear();this.bulkReview=null;this.message=`已${review.suspended?'暂停':'恢复'} ${changed} 张卡片，原评分保留`;});}
 private async checkEvidence(c:Card,el:HTMLElement){const file=this.app.vault.getAbstractFileByPath(c.sourcePath);if(!(file instanceof TFile)){el.textContent='来源已移动或不存在；卡片和学习进度仍然保留';return;}try{const found=locateEvidence(await this.app.vault.read(file),c.sourceRef!.excerpt);el.textContent=found.status==='present'?`保存时的原文仍在 · 当前第 ${found.line+1} 行`:'原文已变化，或原句已移除。请打开来源核对；本卡答案与学习进度保持不变。';}catch{el.textContent='来源读取失败，卡片和进度未改动';}}
 private async revealSource(source:Card|Passage,current:()=>boolean){await this.run(async()=>{if(!current())return;await this.locateSource(source,()=>!this.closed&&current());},()=>{});}
 private async locateSource(source:Card|Passage,current:()=>boolean=()=>!this.closed){
  const path='sourcePath' in source?source.sourcePath:source.path,file=this.app.vault.getAbstractFileByPath(path);
  if(!(file instanceof TFile))throw new Error('来源笔记已移动或删除，请返回学习后刷新。');
  const mtime=file.stat.mtime,size=file.stat.size,text=await this.app.vault.read(file);if(!current())return;
  if(this.app.vault.getAbstractFileByPath(path)!==file||file.path!==path||file.stat.mtime!==mtime||file.stat.size!==size)throw new Error('来源正在变化，请稍后重新揭晓。');
  const line='sourcePath' in source?resolveCardSourceLine(text,source):resolvePassageSourceLine(text,source);
  const leaves=this.app.workspace.getLeavesOfType('markdown').filter(leaf=>leaf.view.containerEl.closest('.mod-root'));
  const leaf=leaves.find(l=>(l.view as MarkdownView).file?.path===path)||leaves.find(l=>(l.view as MarkdownView).file?.path===this.host.currentPath)||leaves[0]||this.app.workspace.getLeaf('tab');
  if(!current())return;await leaf.openFile(file,{active:true,eState:{line}});
  if(current())leaf.setEphemeralState({line});
 }
 private async openSource(c:Card){try{await this.locateSource(c);}catch(e){new Notice(e instanceof Error?e.message:'无法打开来源，请稍后重试。');}}
}
